import { TaskflowContent } from "./types";

export const aiEngineerTaskflow: TaskflowContent = {
  slug: "ai-engineer",
  title: "AI Engineer",
  nodes: [
    // 1. Foundations
    { id: "foundations", kind: "milestone", label: "Foundations",
      description: "Learn core mathematics and programming variables necessary for writing artificial intelligence systems.",
      position: { x: 60, y: 0 } },
    { id: "ai-python", kind: "subtopic", label: "Python",
      description: "The primary programming language for artificial intelligence and data science libraries.",
      links: [{ title: "Python Website", url: "https://www.python.org/" }],
      position: { x: 380, y: 0 } },
    { id: "ai-linear-algebra", kind: "subtopic", label: "Linear Algebra",
      description: "Understand vectors, matrices, and tensor structures supporting core neural network calculations.",
      links: [{ title: "Khan Academy Linear Algebra", url: "https://www.khanacademy.org/math/linear-algebra" }],
      position: { x: 380, y: 55 } },
    { id: "ai-probability-stats", kind: "subtopic", label: "Probability & Statistics",
      description: "Learn mathematical distribution shapes, variance, and hypothesis tests to inspect model data.",
      links: [{ title: "Khan Academy Statistics", url: "https://www.khanacademy.org/math/statistics-probability" }],
      position: { x: 380, y: 110 } },

    // 2. Machine Learning Basics
    { id: "ml-basics", kind: "milestone", label: "Machine Learning Basics",
      description: "Understand classic algorithmic classification, regression, and system parameters.",
      position: { x: 60, y: 220 } },
    { id: "ai-supervised-learning", kind: "subtopic", label: "Supervised Learning",
      description: "Train classification and regression models using labeled datasets.",
      links: [{ title: "Scikit-Learn Supervised docs", url: "https://scikit-learn.org/stable/supervised_learning.html" }],
      position: { x: 380, y: 220 } },
    { id: "ai-unsupervised-learning", kind: "subtopic", label: "Unsupervised Learning",
      description: "Find latent structures in unlabeled data using clustering and PCA dimension reduction.",
      links: [{ title: "Scikit-Learn Unsupervised docs", url: "https://scikit-learn.org/stable/unsupervised_learning.html" }],
      position: { x: 380, y: 275 } },
    { id: "ai-model-evaluation", kind: "subtopic", label: "Model Evaluation",
      description: "Verify model performance using cross-validation and confusion matrix statistics (F1, AUC).",
      links: [{ title: "Scikit-Learn Model Selection", url: "https://scikit-learn.org/stable/model_selection.html" }],
      position: { x: 380, y: 330 } },

    // 3. Deep Learning
    { id: "deep-learning", kind: "milestone", label: "Deep Learning",
      description: "Build deep neural network architectures mimicking complex hierarchical representations.",
      position: { x: 60, y: 440 } },
    { id: "ai-neural-networks", kind: "subtopic", label: "Neural Networks",
      description: "Learn backpropagation calculus, activation functions, and layer configurations.",
      links: [{ title: "3Blue1Brown Neural Networks", url: "https://www.3blue1brown.com/topics/neural-networks" }],
      position: { x: 380, y: 440 } },
    { id: "ai-pytorch", kind: "subtopic", label: "PyTorch",
      description: "A flexible, open-source machine learning framework developed by Meta AI.",
      links: [{ title: "PyTorch Website", url: "https://pytorch.org/" }],
      position: { x: 380, y: 495 } },
    { id: "ai-tensorflow", kind: "subtopic", label: "TensorFlow",
      description: "An end-to-end open-source platform for deep learning developed by Google.",
      links: [{ title: "TensorFlow Website", url: "https://www.tensorflow.org/" }],
      position: { x: 380, y: 550 } },

    // 4. LLMs & Prompting
    { id: "llms-prompting", kind: "milestone", label: "LLMs & Prompting",
      description: "Understand Transformer architectures and prompt strategies.",
      position: { x: 60, y: 660 } },
    { id: "ai-transformers", kind: "subtopic", label: "Transformers",
      description: "Learn attention mechanisms and sequence modeling foundation structures (GPT, BERT).",
      links: [{ title: "Hugging Face Transformers Docs", url: "https://huggingface.co/docs/transformers/index" }],
      position: { x: 380, y: 660 } },
    { id: "ai-prompt-engineering", kind: "subtopic", label: "Prompt Engineering",
      description: "Optimize generative query templates using system messages, chain-of-thought, and few-shot designs.",
      links: [{ title: "Prompt Engineering Guide", url: "https://www.promptingguide.ai/" }],
      position: { x: 380, y: 715 } },
    { id: "ai-fine-tuning", kind: "subtopic", label: "Fine-tuning",
      description: "Train pretrained models on specific niche dataset updates (LoRA, QLoRA).",
      links: [{ title: "Hugging Face Fine-tuning Guide", url: "https://huggingface.co/docs/transformers/training" }],
      position: { x: 380, y: 770 } },

    // 5. Deployment & Tools
    { id: "deployment-tools", kind: "milestone", label: "Deployment & Tools",
      description: "Host model configurations and orchestrate real-time AI user query systems.",
      position: { x: 60, y: 880 } },
    { id: "ai-vector-databases", kind: "subtopic", label: "Vector Databases",
      description: "Store high-dimension embedding coordinates to run semantic searches (Pinecone, Chroma).",
      links: [{ title: "Chroma DB Website", url: "https://www.trychroma.com/" }],
      position: { x: 380, y: 880 } },
    { id: "ai-langchain", kind: "subtopic", label: "LangChain",
      description: "A framework to build software pipelines chaining language model queries with external tools.",
      links: [{ title: "LangChain Website", url: "https://www.langchain.com/" }],
      position: { x: 380, y: 935 } },
    { id: "ai-mlops-basics", kind: "subtopic", label: "MLOps Basics",
      description: "Manage deployment runs, logging models, and data pipeline versioning controls.",
      links: [{ title: "MLflow Website", url: "https://mlflow.org/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-foundations-ml-basics", source: "foundations", target: "ml-basics" },
    { id: "e-ml-basics-deep-learning", source: "ml-basics", target: "deep-learning" },
    { id: "e-deep-learning-llms-prompting", source: "deep-learning", target: "llms-prompting" },
    { id: "e-llms-prompting-deployment-tools", source: "llms-prompting", target: "deployment-tools" },
  ],
};
