import { TaskflowContent } from "./types";

export const androidTaskflow: TaskflowContent = {
  slug: "android",
  title: "Android",
  nodes: [
    // 1. Language Choice
    { id: "language-choice", kind: "milestone", label: "Language Choice",
      description: "Pick an Android software language to write your app logic and compile binaries.",
      position: { x: 60, y: 0 } },
    { id: "andr-kotlin", kind: "subtopic", label: "Kotlin",
      description: "Google's preferred modern language for Android, featuring concise syntax and null safety.",
      links: [{ title: "Kotlin Website", url: "https://kotlinlang.org/" }],
      position: { x: 380, y: 0 } },
    { id: "andr-java", kind: "subtopic", label: "Java",
      description: "The legacy language for Android development, still widely used in historical codebases.",
      links: [{ title: "Oracle Java Website", url: "https://www.oracle.com/java/" }],
      position: { x: 380, y: 55 } },

    // 2. Android Basics
    { id: "android-basics", kind: "milestone", label: "Android Basics",
      description: "Learn core components that run on Android screens and compile views.",
      position: { x: 60, y: 220 } },
    { id: "andr-activities-fragments", kind: "subtopic", label: "Activities & Fragments",
      description: "Understand page lifecycles, user screens, and component nesting architectures.",
      links: [{ title: "Android Developers: Activity guide", url: "https://developer.android.com/guide/components/activities/intro-activities" }],
      position: { x: 380, y: 220 } },
    { id: "andr-layouts-xml", kind: "subtopic", label: "Layouts (XML)",
      description: "Structure static screen elements using standard Android layout xml templates.",
      links: [{ title: "Android Developers: XML layouts", url: "https://developer.android.com/guide/topics/ui/declaring-layout" }],
      position: { x: 380, y: 275 } },
    { id: "andr-jetpack-compose", kind: "subtopic", label: "Jetpack Compose",
      description: "Android's modern declarative UI toolkit for building native layouts with Kotlin functions.",
      links: [{ title: "Android Developers: Jetpack Compose", url: "https://developer.android.com/compose" }],
      position: { x: 380, y: 330 } },

    // 3. App Architecture
    { id: "app-architecture", kind: "milestone", label: "App Architecture",
      description: "Structure native app modules using scalable, testable structural blueprints.",
      position: { x: 60, y: 440 } },
    { id: "andr-mvvm", kind: "subtopic", label: "MVVM",
      description: "Model-View-ViewModel paradigm separating UI controllers from database and data fetching layers.",
      links: [{ title: "Android Developers: Architecture Guide", url: "https://developer.android.com/topic/architecture" }],
      position: { x: 380, y: 440 } },
    { id: "andr-viewmodel-livedata", kind: "subtopic", label: "ViewModel & LiveData",
      description: "Retain UI state values during configuration runs and observe variables reactively.",
      links: [{ title: "Android Developers: ViewModel Docs", url: "https://developer.android.com/topic/libraries/architecture/viewmodel" }],
      position: { x: 380, y: 495 } },
    { id: "andr-dependency-injection", kind: "subtopic", label: "Dependency Injection (Hilt)",
      description: "Inject component dependencies automatically to separate class instances.",
      links: [{ title: "Android Developers: Hilt DI Guide", url: "https://developer.android.com/training/dependency-injection/hilt-android" }],
      position: { x: 380, y: 550 } },

    // 4. Data & Networking
    { id: "data-networking", kind: "milestone", label: "Data & Networking",
      description: "Connect to database tables and query remote backend servers.",
      position: { x: 60, y: 660 } },
    { id: "andr-room-database", kind: "subtopic", label: "Room Database",
      description: "An abstraction layer over SQLite for running persistent local database tables.",
      links: [{ title: "Android Developers: Room Docs", url: "https://developer.android.com/training/data-storage/room" }],
      position: { x: 380, y: 660 } },
    { id: "andr-retrofit", kind: "subtopic", label: "Retrofit",
      description: "A type-safe REST client for Android and Java to handle server requests.",
      links: [{ title: "Retrofit Website", url: "https://square.github.io/retrofit/" }],
      position: { x: 380, y: 715 } },
    { id: "andr-coroutines", kind: "subtopic", label: "Coroutines",
      description: "Write asynchronous, non-blocking code in Kotlin to handle long-running operations.",
      links: [{ title: "Kotlin Coroutines Guide", url: "https://kotlinlang.org/docs/coroutines-overview.html" }],
      position: { x: 380, y: 770 } },

    // 5. Publishing
    { id: "publishing", kind: "milestone", label: "Publishing",
      description: "Test app modules, sign binaries, and publish them to users.",
      position: { x: 60, y: 880 } },
    { id: "andr-testing", kind: "subtopic", label: "Testing",
      description: "Verify app states and components using Junit assertions and Android instrumentation.",
      links: [{ title: "Android Developers: Test Guide", url: "https://developer.android.com/training/testing" }],
      position: { x: 380, y: 880 } },
    { id: "andr-play-store", kind: "subtopic", label: "Play Store Guidelines",
      description: "Understand Google Play Store policies and layout rules.",
      links: [{ title: "Google Play Console", url: "https://play.google.com/console/about/" }],
      position: { x: 380, y: 935 } },
    { id: "andr-app-signing", kind: "subtopic", label: "App Signing",
      description: "Sign application bundles (AAB) using digital keys to secure updates.",
      links: [{ title: "Android Developers: App Signing", url: "https://developer.android.com/studio/publish/app-signing" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-language-choice-android-basics", source: "language-choice", target: "android-basics" },
    { id: "e-android-basics-app-architecture", source: "android-basics", target: "app-architecture" },
    { id: "e-app-architecture-data-networking", source: "app-architecture", target: "data-networking" },
    { id: "e-data-networking-publishing", source: "data-networking", target: "publishing" },
  ],
};
