import { TaskflowContent } from "./types";

export const awsTaskflow: TaskflowContent = {
  slug: "aws",
  title: "AWS",
  nodes: [
    // 1. Foundations
    { id: "aws-foundations", kind: "milestone", label: "Foundations",
      description: "Understand permission hierarchies, resource zones, and terminal controls.",
      position: { x: 60, y: 0 } },
    { id: "aws-iam", kind: "subtopic", label: "IAM",
      description: "Manage users permissions, access groups, role definitions, and credentials constraints.",
      links: [{ title: "AWS IAM Documentation", url: "https://docs.aws.amazon.com/iam/" }],
      position: { x: 380, y: 0 } },
    { id: "aws-regions-azs", kind: "subtopic", label: "Regions & AZs",
      description: "Deploy resources across global geographic regions and isolated Availability Zones.",
      links: [{ title: "AWS Global Infrastructure Guide", url: "https://aws.amazon.com/about-aws/global-infrastructure/" }],
      position: { x: 380, y: 55 } },
    { id: "aws-cli", kind: "subtopic", label: "AWS CLI",
      description: "Manage infrastructure resources programmatically from your terminal shell.",
      links: [{ title: "AWS CLI User Guide", url: "https://docs.aws.amazon.com/cli/" }],
      position: { x: 380, y: 110 } },

    // 2. Compute
    { id: "aws-compute", kind: "milestone", label: "Compute",
      description: "Launch virtual machine servers, run serverless scripts, and deploy apps.",
      position: { x: 60, y: 220 } },
    { id: "aws-ec2", kind: "subtopic", label: "EC2",
      description: "Configure virtual server instances, manage storage volumes, and assign security groups.",
      links: [{ title: "AWS EC2 Documentation", url: "https://docs.aws.amazon.com/ec2/" }],
      position: { x: 380, y: 220 } },
    { id: "aws-lambda", kind: "subtopic", label: "Lambda",
      description: "Run serverless code functions in response to incoming HTTP or database events.",
      links: [{ title: "AWS Lambda Documentation", url: "https://docs.aws.amazon.com/lambda/" }],
      position: { x: 380, y: 275 } },
    { id: "aws-elastic-beanstalk", kind: "subtopic", label: "Elastic Beanstalk",
      description: "Deploy and scale web application stacks automatically, without managing underlying OS configs.",
      links: [{ title: "AWS Elastic Beanstalk Docs", url: "https://docs.aws.amazon.com/elasticbeanstalk/" }],
      position: { x: 380, y: 330 } },

    // 3. Storage & Databases
    { id: "aws-storage-databases", kind: "milestone", label: "Storage & Databases",
      description: "Persist files, connect relational databases, and query no-sql tables.",
      position: { x: 60, y: 440 } },
    { id: "aws-s3", kind: "subtopic", label: "S3",
      description: "Store documents, image files, and static assets in highly available object storage buckets.",
      links: [{ title: "AWS S3 Documentation", url: "https://docs.aws.amazon.com/s3/" }],
      position: { x: 380, y: 440 } },
    { id: "aws-rds", kind: "subtopic", label: "RDS",
      description: "Launch managed relational databases like PostgreSQL or MySQL with automatic backups.",
      links: [{ title: "AWS RDS Documentation", url: "https://docs.aws.amazon.com/rds/" }],
      position: { x: 380, y: 495 } },
    { id: "aws-dynamodb", kind: "subtopic", label: "DynamoDB",
      description: "Query high-speed, key-value NoSQL database tables with single-digit millisecond latency.",
      links: [{ title: "AWS DynamoDB Documentation", url: "https://docs.aws.amazon.com/dynamodb/" }],
      position: { x: 380, y: 550 } },

    // 4. Networking
    { id: "aws-networking", kind: "milestone", label: "Networking",
      description: "Create private cloud networks, map DNS records, and accelerate content loading.",
      position: { x: 60, y: 660 } },
    { id: "aws-vpc", kind: "subtopic", label: "VPC",
      description: "Isolate AWS resources inside custom virtual private networks, subnets, and gateways.",
      links: [{ title: "AWS VPC Documentation", url: "https://docs.aws.amazon.com/vpc/" }],
      position: { x: 380, y: 660 } },
    { id: "aws-route53", kind: "subtopic", label: "Route 53",
      description: "Manage DNS registrations, route domain requests, and check server health states.",
      links: [{ title: "AWS Route 53 Documentation", url: "https://docs.aws.amazon.com/route53/" }],
      position: { x: 380, y: 715 } },
    { id: "aws-cloudfront", kind: "subtopic", label: "CloudFront",
      description: "Distribute static assets and API responses globally using low-latency content delivery networks (CDN).",
      links: [{ title: "AWS CloudFront Documentation", url: "https://docs.aws.amazon.com/cloudfront/" }],
      position: { x: 380, y: 770 } },

    // 5. DevOps Tools
    { id: "aws-devops-tools", kind: "milestone", label: "DevOps Tools",
      description: "Declare infrastructure via code configurations, collect metrics, and orchestrate containers.",
      position: { x: 60, y: 880 } },
    { id: "aws-cloudformation", kind: "subtopic", label: "CloudFormation",
      description: "Declare AWS resources using templates to provision infrastructure automatically.",
      links: [{ title: "AWS CloudFormation Docs", url: "https://docs.aws.amazon.com/cloudformation/" }],
      position: { x: 380, y: 880 } },
    { id: "aws-cloudwatch", kind: "subtopic", label: "CloudWatch",
      description: "Monitor cloud services performance, collect resource logs, and trigger alarm thresholds.",
      links: [{ title: "AWS CloudWatch Documentation", url: "https://docs.aws.amazon.com/cloudwatch/" }],
      position: { x: 380, y: 935 } },
    { id: "aws-ecs-eks", kind: "subtopic", label: "ECS/EKS",
      description: "Run container applications using ECS or run managed Kubernetes clusters via EKS.",
      links: [{ title: "AWS ECS Documentation", url: "https://docs.aws.amazon.com/ecs/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-aws-foundations-aws-compute", source: "aws-foundations", target: "aws-compute" },
    { id: "e-aws-compute-aws-storage-databases", source: "aws-compute", target: "aws-storage-databases" },
    { id: "e-aws-storage-databases-aws-networking", source: "aws-storage-databases", target: "aws-networking" },
    { id: "e-aws-networking-aws-devops-tools", source: "aws-networking", target: "aws-devops-tools" },
  ],
};
