import { TaskflowContent } from "./types";

export const backendTaskflow: TaskflowContent = {
  slug: "backend",
  title: "Backend",
  nodes: [
    // 1. Pick a Language
    { id: "lang", kind: "milestone", label: "Pick a Language",
      description: "Backend development requires a server-side programming language to run logic and handle databases.",
      position: { x: 60, y: 0 } },
    { id: "lang-python", kind: "subtopic", label: "Python",
      description: "A versatile, readable programming language popular for web backends (Django, FastAPI).",
      links: [{ title: "Python Website", url: "https://www.python.org/" }],
      position: { x: 380, y: 0 } },
    { id: "lang-nodejs", kind: "subtopic", label: "Node.js",
      description: "A JavaScript runtime built on Chrome's V8 engine, used for writing fast, scalable backends.",
      links: [{ title: "Node.js Website", url: "https://nodejs.org/" }],
      position: { x: 380, y: 55 } },
    { id: "lang-java", kind: "subtopic", label: "Java",
      description: "A robust, object-oriented language widely used in enterprise-scale backend environments (Spring Boot).",
      links: [{ title: "Java Website", url: "https://www.java.com/" }],
      position: { x: 380, y: 110 } },
    { id: "lang-go", kind: "subtopic", label: "Go",
      description: "An open-source language developed by Google, optimized for high performance and concurrency.",
      links: [{ title: "Go Website", url: "https://go.dev/" }],
      position: { x: 380, y: 165 } },

    // 2. Version Control
    { id: "vcs", kind: "milestone", label: "Version Control",
      description: "System to track code changes and collaborate with developers.",
      position: { x: 60, y: 220 } },
    { id: "vcs-git", kind: "subtopic", label: "Git",
      description: "A distributed version control system to manage project history and source files.",
      links: [{ title: "Git Website", url: "https://git-scm.com/" }],
      position: { x: 380, y: 220 } },
    { id: "vcs-github", kind: "subtopic", label: "GitHub/GitLab",
      description: "Online code hosting platforms built around Git for sharing code and tracking issue revisions.",
      links: [{ title: "GitHub Website", url: "https://github.com/" }],
      position: { x: 380, y: 275 } },

    // 3. Relational Databases
    { id: "db", kind: "milestone", label: "Relational Databases",
      description: "Store structured datasets in tables linked by relationships.",
      position: { x: 60, y: 440 } },
    { id: "db-postgres", kind: "subtopic", label: "PostgreSQL",
      description: "A powerful, open-source object-relational database system known for reliability and scalability.",
      links: [{ title: "PostgreSQL Website", url: "https://www.postgresql.org/" }],
      position: { x: 380, y: 440 } },
    { id: "db-mysql", kind: "subtopic", label: "MySQL",
      description: "A popular, fast SQL relational database management system used by many web applications.",
      links: [{ title: "MySQL Website", url: "https://www.mysql.com/" }],
      position: { x: 380, y: 495 } },
    { id: "db-orms", kind: "subtopic", label: "ORMs",
      description: "Object-Relational Mapping libraries (like Prisma or Hibernate) to write SQL using programming objects.",
      links: [{ title: "Prisma Website", url: "https://www.prisma.io/" }],
      position: { x: 380, y: 550 } },

    // 4. APIs
    { id: "apis", kind: "milestone", label: "APIs",
      description: "Application Programming Interfaces allow client devices to query backend servers for resources.",
      position: { x: 60, y: 660 } },
    { id: "apis-rest", kind: "subtopic", label: "REST",
      description: "Representational State Transfer layout convention using HTTP verbs and JSON/XML objects.",
      links: [{ title: "MDN REST API Guide", url: "https://developer.mozilla.org/en-US/docs/Glossary/REST" }],
      position: { x: 380, y: 660 } },
    { id: "apis-graphql", kind: "subtopic", label: "GraphQL",
      description: "A query language for APIs that lets clients request exactly the fields they need.",
      links: [{ title: "GraphQL Website", url: "https://graphql.org/" }],
      position: { x: 380, y: 715 } },
    { id: "apis-auth", kind: "subtopic", label: "Authentication (JWT/OAuth)",
      description: "Secure APIs with stateful cookies, JWT tokens, or third-party login protocols like OAuth.",
      links: [{ title: "JWT.io Website", url: "https://jwt.io/" }],
      position: { x: 380, y: 770 } },

    // 5. Caching
    { id: "caching", kind: "milestone", label: "Caching",
      description: "Store high-frequency query results temporarily to reduce database operations.",
      position: { x: 60, y: 880 } },
    { id: "caching-redis", kind: "subtopic", label: "Redis",
      description: "An open-source in-memory key-value data store used as a high-speed database, cache, and message broker.",
      links: [{ title: "Redis Website", url: "https://redis.io/" }],
      position: { x: 380, y: 880 } },
    { id: "caching-cdn", kind: "subtopic", label: "CDN",
      description: "Content Delivery Networks that store frontend static files closer to geographic users.",
      links: [{ title: "Cloudflare CDN Info", url: "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/" }],
      position: { x: 380, y: 935 } },

    // 6. Web Security
    { id: "security", kind: "milestone", label: "Web Security",
      description: "Defend backend systems from unauthorized access, cross-origin scripts, or database injections.",
      position: { x: 60, y: 1100 } },
    { id: "sec-https", kind: "subtopic", label: "HTTPS/SSL",
      description: "Encrypt network traffic between browser clients and servers using TLS/SSL certificates.",
      links: [{ title: "LetsEncrypt Website", url: "https://letsencrypt.org/" }],
      position: { x: 380, y: 1100 } },
    { id: "sec-cors", kind: "subtopic", label: "CORS",
      description: "Cross-Origin Resource Sharing manages permissions for scripts on other domains querying your API.",
      links: [{ title: "MDN CORS Guide", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS" }],
      position: { x: 380, y: 1155 } },
    { id: "sec-owasp", kind: "subtopic", label: "OWASP Top 10",
      description: "Standard security guide listing the most critical web application security risks.",
      links: [{ title: "OWASP Website", url: "https://owasp.org/www-project-top-ten/" }],
      position: { x: 380, y: 1210 } },

    // 7. Testing
    { id: "testing", kind: "milestone", label: "Testing",
      description: "Validate code logic correctness and database connectivity before deployment.",
      position: { x: 60, y: 1320 } },
    { id: "test-unit", kind: "subtopic", label: "Unit Testing",
      description: "Test logic units in isolation without querying database dependencies.",
      links: [{ title: "Vitest Website", url: "https://vitest.dev/" }],
      position: { x: 380, y: 1320 } },
    { id: "test-int", kind: "subtopic", label: "Integration Testing",
      description: "Test combined logic components and queries directly against test database environments.",
      links: [{ title: "Jest Website", url: "https://jestjs.io/" }],
      position: { x: 380, y: 1375 } },

    // 8. Containerization
    { id: "containerization", kind: "milestone", label: "Containerization",
      description: "Bundle software engines and dependencies into packages that compile identically on any device.",
      position: { x: 60, y: 1540 } },
    { id: "cont-docker", kind: "subtopic", label: "Docker",
      description: "Build, run, and host isolated developer environment containers.",
      links: [{ title: "Docker Website", url: "https://www.docker.com/" }],
      position: { x: 380, y: 1540 } },
    { id: "cont-compose", kind: "subtopic", label: "Docker Compose",
      description: "Run multi-container network environments (e.g. API + database + cache) using yaml configurations.",
      links: [{ title: "Docker Compose Docs", url: "https://docs.docker.com/compose/" }],
      position: { x: 380, y: 1595 } },
  ],
  edges: [
    { id: "e-lang-vcs", source: "lang", target: "vcs" },
    { id: "e-vcs-db", source: "vcs", target: "db" },
    { id: "e-db-apis", source: "db", target: "apis" },
    { id: "e-apis-caching", source: "apis", target: "caching" },
    { id: "e-caching-security", source: "caching", target: "security" },
    { id: "e-security-testing", source: "security", target: "testing" },
    { id: "e-testing-container", source: "testing", target: "containerization" },
  ],
};
