import { TaskflowContent } from "./types";

export const computerScienceTaskflow: TaskflowContent = {
  slug: "computer-science",
  title: "Computer Science",
  nodes: [
    // 1. Foundations
    { id: "cs-foundations", kind: "milestone", label: "Foundations",
      description: "Master number bases, logic gates, and the internal components of CPUs.",
      position: { x: 60, y: 0 } },
    { id: "cs-binary-number-systems", kind: "subtopic", label: "Binary & Number Systems",
      description: "Differentiate decimal values from binary, octal, and hexadecimal representation rules.",
      links: [{ title: "Khan Academy: Binary Numbers", url: "https://www.khanacademy.org/computing/computers-and-internet/x1a2d56a7:digital-information/x1a2d56a7:binary-numbers/a:bits-and-binary" }],
      position: { x: 380, y: 0 } },
    { id: "cs-logic-gates", kind: "subtopic", label: "Logic Gates",
      description: "Map input signals using Boolean operations like AND, OR, NOT, XOR, and NAND gates.",
      links: [{ title: "Logic Gates Guide", url: "https://www.sciencedirect.com/topics/engineering/logic-gates" }],
      position: { x: 380, y: 55 } },
    { id: "cs-computer-architecture", kind: "subtopic", label: "Computer Architecture",
      description: "Examine execution cycles, registers allocations, ALU designs, and memory structures.",
      links: [{ title: "CPU Architecture Overview", url: "https://www.sciencedirect.com/topics/computer-science/computer-architecture" }],
      position: { x: 380, y: 110 } },

    // 2. Data Structures
    { id: "cs-data-structures", kind: "milestone", label: "Data Structures",
      description: "Organize data using standard structures like arrays, queues, and tree hierarchies.",
      position: { x: 60, y: 220 } },
    { id: "cs-arrays-linked-lists", kind: "subtopic", label: "Arrays & Linked Lists",
      description: "Compare contiguous index lists to dynamic pointers chains in memory allocations.",
      links: [{ title: "GeeksforGeeks Data Structures Guide", url: "https://www.geeksforgeeks.org/data-structures/" }],
      position: { x: 380, y: 220 } },
    { id: "cs-stacks-queues", kind: "subtopic", label: "Stacks & Queues",
      description: "Differentiate LIFO stack operations from FIFO queue buffers schemas.",
      links: [{ title: "GeeksforGeeks: Stack and Queue", url: "https://www.geeksforgeeks.org/stack-data-structure/" }],
      position: { x: 380, y: 275 } },
    { id: "cs-trees-graphs", kind: "subtopic", label: "Trees & Graphs",
      description: "Traverse hierarchical node trees and network graphs using depth or breadth strategies.",
      links: [{ title: "GeeksforGeeks: Graph Data Structure", url: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/" }],
      position: { x: 380, y: 330 } },

    // 3. Algorithms
    { id: "cs-algorithms", kind: "milestone", label: "Algorithms",
      description: "Apply standard sorting procedures, search items, and loop execution self-references.",
      position: { x: 60, y: 440 } },
    { id: "cs-sorting-algorithms", kind: "subtopic", label: "Sorting Algorithms",
      description: "Compare partition sorts like Quick Sort and Merge Sort to linear bubble algorithms.",
      links: [{ title: "GeeksforGeeks: Sorting Algorithms", url: "https://www.geeksforgeeks.org/sorting-algorithms/" }],
      position: { x: 380, y: 440 } },
    { id: "cs-searching-algorithms", kind: "subtopic", label: "Searching Algorithms",
      description: "Find items quickly using logarithmic Binary Search or simple linear scan routines.",
      links: [{ title: "GeeksforGeeks: Searching Algorithms", url: "https://www.geeksforgeeks.org/searching-algorithms/" }],
      position: { x: 380, y: 495 } },
    { id: "cs-recursion", kind: "subtopic", label: "Recursion",
      description: "Solve complex problems by breaking them into self-calling base-case statements.",
      links: [{ title: "GeeksforGeeks: Recursion", url: "https://www.geeksforgeeks.org/introduction-to-recursion-data-structure-and-algorithm-tutorials/" }],
      position: { x: 380, y: 550 } },

    // 4. Complexity
    { id: "cs-complexity", kind: "milestone", label: "Complexity",
      description: "Measure code efficiency limits, loop growth rates, and space consumption bounds.",
      position: { x: 60, y: 660 } },
    { id: "cs-big-o-notation", kind: "subtopic", label: "Big-O Notation",
      description: "Classify execution runtime boundaries as a mathematical function of input size N.",
      links: [{ title: "MIT Big O Guide", url: "https://web.mit.edu/16.070/www/lecture/big_o.pdf" }],
      position: { x: 380, y: 660 } },
    { id: "cs-time-space-complexity", kind: "subtopic", label: "Time vs Space Complexity",
      description: "Weigh runtime speedups against memory utilization increases in systems.",
      links: [{ title: "GeeksforGeeks: Analysis of Algorithms", url: "https://www.geeksforgeeks.org/analysis-of-algorithms-set-1-asymptotic-analysis/" }],
      position: { x: 380, y: 715 } },
    { id: "cs-algorithm-analysis", kind: "subtopic", label: "Algorithm Analysis",
      description: "Calculate best, average, and worst-case resource execution rates using math constraints.",
      links: [{ title: "Berkeley: Algorithmic Complexity", url: "https://inst.eecs.berkeley.edu/~cs61bl/su15/materials/lab/lab13.html" }],
      position: { x: 380, y: 770 } },

    // 5. Theory
    { id: "cs-theory", kind: "milestone", label: "Theory",
      description: "Learn core OS components, relational storage laws, and language translations pipelines.",
      position: { x: 60, y: 880 } },
    { id: "cs-operating-systems-basics", kind: "subtopic", label: "Operating Systems Basics",
      description: "Understand scheduling mechanisms, virtual memory, threads synchronization, and lockouts.",
      links: [{ title: "OS Three Easy Pieces", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/" }],
      position: { x: 380, y: 880 } },
    { id: "cs-databases-theory", kind: "subtopic", label: "Databases Theory",
      description: "Understand ACID properties, schema normalization forms, and transaction serialization levels.",
      links: [{ title: "Stanford Database Course", url: "https://online.stanford.edu/courses/soe-ydatabases-databases" }],
      position: { x: 380, y: 935 } },
    { id: "cs-compilers-basics", kind: "subtopic", label: "Compilers Basics",
      description: "Deconstruct source strings into tokens, parser trees, and machine assembly directives.",
      links: [{ title: "Stanford Compiler Class Notes", url: "https://web.stanford.edu/class/archive/cs/cs143/cs143.1128/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-cs-foundations-cs-data-structures", source: "cs-foundations", target: "cs-data-structures" },
    { id: "e-cs-data-structures-cs-algorithms", source: "cs-data-structures", target: "cs-algorithms" },
    { id: "e-cs-algorithms-cs-complexity", source: "cs-algorithms", target: "cs-complexity" },
    { id: "e-cs-complexity-cs-theory", source: "cs-complexity", target: "cs-theory" },
  ],
};
