import { TaskflowContent } from "./types";

export const cppTaskflow: TaskflowContent = {
  slug: "cpp",
  title: "C++",
  nodes: [
    // 1. Basics
    { id: "cpp-basics", kind: "milestone", label: "Basics",
      description: "Learn compiler entry points, strict type parameters, and reference pointer variables.",
      position: { x: 60, y: 0 } },
    { id: "cpp-syntax-variables", kind: "subtopic", label: "Syntax & Variables",
      description: "Compile main routines, import header libraries, and configure primitive data variables.",
      links: [{ title: "cppreference: Language Basics", url: "https://en.cppreference.com/w/cpp/language" }],
      position: { x: 380, y: 0 } },
    { id: "cpp-functions", kind: "subtopic", label: "Functions",
      description: "Define argument structures, return values, overload names, and default parameters.",
      links: [{ title: "cppreference: Functions", url: "https://en.cppreference.com/w/cpp/language/functions" }],
      position: { x: 380, y: 55 } },
    { id: "cpp-pointers-references", kind: "subtopic", label: "Pointers & References",
      description: "Manage memory addresses using raw pointers and create variable aliases via references.",
      links: [{ title: "cppreference: Reference Declarations", url: "https://en.cppreference.com/w/cpp/language/reference" }],
      position: { x: 380, y: 110 } },

    // 2. OOP
    { id: "cpp-oop", kind: "milestone", label: "OOP",
      description: "Model objects using classes, override parent layouts, and resolve runtime interfaces.",
      position: { x: 60, y: 220 } },
    { id: "cpp-classes-objects", kind: "subtopic", label: "Classes & Objects",
      description: "Define object schemas, write constructors/destructors, and encapsulate variables.",
      links: [{ title: "cppreference: Classes", url: "https://en.cppreference.com/w/cpp/language/classes" }],
      position: { x: 380, y: 220 } },
    { id: "cpp-inheritance", kind: "subtopic", label: "Inheritance",
      description: "Extend parent class capabilities using single or multiple inheritance patterns.",
      links: [{ title: "cppreference: Derived Classes", url: "https://en.cppreference.com/w/cpp/language/derived_class" }],
      position: { x: 380, y: 275 } },
    { id: "cpp-polymorphism", kind: "subtopic", label: "Polymorphism",
      description: "Resolve function calls at runtime using virtual methods and override behaviors.",
      links: [{ title: "cppreference: virtual Member Functions", url: "https://en.cppreference.com/w/cpp/language/virtual" }],
      position: { x: 380, y: 330 } },

    // 3. Memory Management
    { id: "cpp-memory-management", kind: "milestone", label: "Memory Management",
      description: "Allocate stack/heap variables, avoid memory leaks, and automate allocations lifecycles.",
      position: { x: 60, y: 440 } },
    { id: "cpp-dynamic-memory", kind: "subtopic", label: "Dynamic Memory (new/delete)",
      description: "Request heap storage allocations using new and free allocations using delete pointers commands.",
      links: [{ title: "cppreference: Memory Allocation Operators", url: "https://en.cppreference.com/w/cpp/memory/new/operator_new" }],
      position: { x: 380, y: 440 } },
    { id: "cpp-smart-pointers", kind: "subtopic", label: "Smart Pointers",
      description: "Manage memory automatically using std::unique_ptr, std::shared_ptr, and std::weak_ptr.",
      links: [{ title: "cppreference: Smart Pointers", url: "https://en.cppreference.com/w/cpp/memory" }],
      position: { x: 380, y: 495 } },
    { id: "cpp-raii", kind: "subtopic", label: "RAII",
      description: "Enforce Resource Acquisition Is Initialization to clean up resources during destructor calls.",
      links: [{ title: "cppreference: RAII Design", url: "https://en.cppreference.com/w/cpp/language/raii" }],
      position: { x: 380, y: 550 } },

    // 4. STL
    { id: "cpp-stl", kind: "milestone", label: "STL",
      description: "Use standard vectors or maps, traverse ranges, and operate sorting algorithms.",
      position: { x: 60, y: 660 } },
    { id: "cpp-vectors-containers", kind: "subtopic", label: "Vectors & Containers",
      description: "Store sequential items in dynamic vectors, sets, or key-value dictionary maps.",
      links: [{ title: "cppreference: Containers Library", url: "https://en.cppreference.com/w/cpp/container" }],
      position: { x: 380, y: 660 } },
    { id: "cpp-iterators", kind: "subtopic", label: "Iterators",
      description: "Traverse elements across STL container layouts using generic iterator pointers.",
      links: [{ title: "cppreference: Iterators Library", url: "https://en.cppreference.com/w/cpp/iterator" }],
      position: { x: 380, y: 715 } },
    { id: "cpp-algorithms-library", kind: "subtopic", label: "Algorithms Library",
      description: "Filter, sort, search, and count elements collections using standard library functions.",
      links: [{ title: "cppreference: Algorithms Library", url: "https://en.cppreference.com/w/cpp/algorithm" }],
      position: { x: 380, y: 770 } },

    // 5. Advanced
    { id: "cpp-advanced", kind: "milestone", label: "Advanced",
      description: "Write generic class templates, copy resource allocations efficiently, and run concurrent threads.",
      position: { x: 60, y: 880 } },
    { id: "cpp-templates", kind: "subtopic", label: "Templates",
      description: "Write type-generic classes and functions compiled dynamically at compile time.",
      links: [{ title: "cppreference: Templates", url: "https://en.cppreference.com/w/cpp/language/templates" }],
      position: { x: 380, y: 880 } },
    { id: "cpp-move-semantics", kind: "subtopic", label: "Move Semantics",
      description: "Transfer resource ownership instead of copying to optimize application speedups.",
      links: [{ title: "cppreference: Move Constructors", url: "https://en.cppreference.com/w/cpp/language/move_constructor" }],
      position: { x: 380, y: 935 } },
    { id: "cpp-multithreading", kind: "subtopic", label: "Multithreading",
      description: "Run concurrent threads using std::thread and protect variables using std::mutex constraints.",
      links: [{ title: "cppreference: Thread Support Library", url: "https://en.cppreference.com/w/cpp/thread" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-cpp-basics-cpp-oop", source: "cpp-basics", target: "cpp-oop" },
    { id: "e-cpp-oop-cpp-memory-management", source: "cpp-oop", target: "cpp-memory-management" },
    { id: "e-cpp-memory-management-cpp-stl", source: "cpp-memory-management", target: "cpp-stl" },
    { id: "e-cpp-stl-cpp-advanced", source: "cpp-stl", target: "cpp-advanced" },
  ],
};
