import { TaskflowContent } from "./types";

export const cyberSecurityTaskflow: TaskflowContent = {
  slug: "cyber-security",
  title: "Cyber Security",
  nodes: [
    // 1. Foundations
    { id: "cs-foundations", kind: "milestone", label: "Foundations",
      description: "Acquire basic systems administration and foundational computer networking understanding.",
      position: { x: 60, y: 0 } },
    { id: "cs-networking-basics", kind: "subtopic", label: "Networking Basics",
      description: "Learn how packets flow across routers, switches, IP addresses, and standard ports.",
      links: [{ title: "Cisco Networking Basics", url: "https://www.cisco.com/c/en/us/solutions/small-business/resource-center/networking/networking-basics.html" }],
      position: { x: 380, y: 0 } },
    { id: "cs-operating-systems", kind: "subtopic", label: "Operating Systems",
      description: "Understand operating system kernels, process execution, file subsystems, and memory allocation.",
      links: [{ title: "OS Course Notes", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/" }],
      position: { x: 380, y: 55 } },
    { id: "cs-linux", kind: "subtopic", label: "Linux",
      description: "Master navigation, user permission levels, shell configurations, and scripting tasks.",
      links: [{ title: "Linux Documentation", url: "https://www.kernel.org/doc/html/latest/" }],
      position: { x: 380, y: 110 } },

    // 2. Security Concepts
    { id: "cs-security-concepts", kind: "milestone", label: "Security Concepts",
      description: "Analyze baseline principles of system integrity, cryptography, and modern threat vectors.",
      position: { x: 60, y: 220 } },
    { id: "cs-cia-triad", kind: "subtopic", label: "CIA Triad",
      description: "Ensure Confidentiality, Integrity, and Availability across data architectures.",
      links: [{ title: "NIST Security Principles", url: "https://csrc.nist.gov/" }],
      position: { x: 380, y: 220 } },
    { id: "cs-cryptography-basics", kind: "subtopic", label: "Cryptography Basics",
      description: "Implement public key encryption, symmetric hashing algorithms, and SSL/TLS keys.",
      links: [{ title: "OpenSSL Documentation", url: "https://www.openssl.org/docs/" }],
      position: { x: 380, y: 275 } },
    { id: "cs-common-attack-types", kind: "subtopic", label: "Common Attack Types",
      description: "Identify phishing attempts, man-in-the-middle captures, DDoS attacks, and buffer overflows.",
      links: [{ title: "MITRE ATT&CK Matrix", url: "https://attack.mitre.org/" }],
      position: { x: 380, y: 330 } },

    // 3. Tools
    { id: "cs-tools", kind: "milestone", label: "Tools",
      description: "Operate standard network auditing, packet inspecting, and vulnerability analysis applications.",
      position: { x: 60, y: 440 } },
    { id: "cs-wireshark", kind: "subtopic", label: "Wireshark",
      description: "Analyze packet headers, TCP handshakes, and application protocol payloads interactively.",
      links: [{ title: "Wireshark User Guide", url: "https://www.wireshark.org/docs/wsug_html_chunked/" }],
      position: { x: 380, y: 440 } },
    { id: "cs-nmap", kind: "subtopic", label: "Nmap",
      description: "Perform host discovery, scan ports, and determine services running on network nodes.",
      links: [{ title: "Nmap Reference Guide", url: "https://nmap.org/book/man.html" }],
      position: { x: 380, y: 495 } },
    { id: "cs-burpsuite", kind: "subtopic", label: "Burp Suite",
      description: "Intercept web server HTTP transactions to audit application APIs and form parameters.",
      links: [{ title: "Burp Suite Docs", url: "https://portswigger.net/burp/documentation" }],
      position: { x: 380, y: 550 } },

    // 4. Application Security
    { id: "cs-app-security", kind: "milestone", label: "Application Security",
      description: "Mitigate application exploits and build secure architectures through testing practices.",
      position: { x: 60, y: 660 } },
    { id: "cs-owasp-top-10", kind: "subtopic", label: "OWASP Top 10",
      description: "Reference the standard list of critical security vulnerabilities impacting modern web services.",
      links: [{ title: "OWASP Top 10 Project", url: "https://owasp.org/www-project-top-ten/" }],
      position: { x: 380, y: 660 } },
    { id: "cs-secure-coding", kind: "subtopic", label: "Secure Coding",
      description: "Sanitize data inputs, manage password hashing, and prevent injection vulnerabilities.",
      links: [{ title: "SEI CERT Coding Standards", url: "https://www.securecoding.cert.org/" }],
      position: { x: 380, y: 715 } },
    { id: "cs-penetration-testing", kind: "subtopic", label: "Penetration Testing",
      description: "Perform simulated attacks to identify system exploits and verify patch effectiveness.",
      links: [{ title: "OSCP Guidelines", url: "https://www.offsec.com/" }],
      position: { x: 380, y: 770 } },

    // 5. Certifications & Practice
    { id: "cs-certifications-practice", kind: "milestone", label: "Certifications & Practice",
      description: "Validate security skills through recognized certificates and hands-on laboratory games.",
      position: { x: 60, y: 880 } },
    { id: "cs-comptia-security-plus", kind: "subtopic", label: "CompTIA Security+",
      description: "Study Core security principles, risk management, and network infrastructure threats.",
      links: [{ title: "CompTIA Security+ Certification", url: "https://www.comptia.org/certifications/security" }],
      position: { x: 380, y: 880 } },
    { id: "cs-ctf-practice", kind: "subtopic", label: "CTF Practice",
      description: "Solve challenges across cryptography, binary exploitation, and reverse engineering.",
      links: [{ title: "CTFTime Platform", url: "https://ctftime.org/" }],
      position: { x: 380, y: 935 } },
    { id: "cs-ceh", kind: "subtopic", label: "CEH",
      description: "Learn ethical hacking methodologies, footprinting, and vulnerability scanning techniques.",
      links: [{ title: "EC-Council CEH", url: "https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-cs-foundations-cs-security-concepts", source: "cs-foundations", target: "cs-security-concepts" },
    { id: "e-cs-security-concepts-cs-tools", source: "cs-security-concepts", target: "cs-tools" },
    { id: "e-cs-tools-cs-app-security", source: "cs-tools", target: "cs-app-security" },
    { id: "e-cs-app-security-cs-certifications-practice", source: "cs-app-security", target: "cs-certifications-practice" },
  ],
};
