import { TaskflowContent } from "./types";

export const dataAnalystTaskflow: TaskflowContent = {
  slug: "data-analyst",
  title: "Data Analyst",
  nodes: [
    // 1. Foundations
    { id: "da-foundations", kind: "milestone", label: "Foundations",
      description: "Master basic calculation sheets, descriptive statistics concepts, and standard database queries.",
      position: { x: 60, y: 0 } },
    { id: "da-excel", kind: "subtopic", label: "Excel",
      description: "Perform lookups, write arithmetic formulas, create pivot tables, and filter workbook datasets.",
      links: [{ title: "Microsoft Excel Support", url: "https://support.microsoft.com/en-us/excel" }],
      position: { x: 380, y: 0 } },
    { id: "da-statistics-basics", kind: "subtopic", label: "Statistics Basics",
      description: "Understand standard deviations, normal distributions, correlation indexes, and probability laws.",
      links: [{ title: "Khan Academy Statistics", url: "https://www.khanacademy.org/math/statistics-probability" }],
      position: { x: 380, y: 55 } },
    { id: "da-sql", kind: "subtopic", label: "SQL",
      description: "Query database tables, filter outputs, join datasets, and calculate fields using aggregate functions.",
      links: [{ title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com/" }],
      position: { x: 380, y: 110 } },

    // 2. Data Manipulation
    { id: "da-data-manipulation", kind: "milestone", label: "Data Manipulation",
      description: "Programmatically filter, restructure, transform, and clean raw dataset shapes.",
      position: { x: 60, y: 220 } },
    { id: "da-python-pandas", kind: "subtopic", label: "Python (Pandas)",
      description: "Employ Pandas DataFrames to filter, aggregate, group, and merge table datasets.",
      links: [{ title: "Pandas Documentation", url: "https://pandas.pydata.org/docs/" }],
      position: { x: 380, y: 220 } },
    { id: "da-data-cleaning", kind: "subtopic", label: "Data Cleaning",
      description: "Handle missing values, parse date formats, drop duplicate records, and filter out outlier values.",
      links: [{ title: "Pandas Cleaning Guide", url: "https://pandas.pydata.org/docs/user_guide/index.html" }],
      position: { x: 380, y: 275 } },
    { id: "da-etl-basics", kind: "subtopic", label: "ETL Basics",
      description: "Understand the Extract, Transform, and Load workflows that ingest and format business datasets.",
      links: [{ title: "AWS ETL Concept Guide", url: "https://aws.amazon.com/what-is/etl/" }],
      position: { x: 380, y: 330 } },

    // 3. Visualization
    { id: "da-visualization", kind: "milestone", label: "Visualization",
      description: "Translate complex numeric datasets into clear, interactive charts, plots, and graphs.",
      position: { x: 60, y: 440 } },
    { id: "da-tableau", kind: "subtopic", label: "Tableau",
      description: "Build interactive data worksheets, connect workbook sources, and compose filter dashboards.",
      links: [{ title: "Tableau Help Center", url: "https://help.tableau.com/" }],
      position: { x: 380, y: 440 } },
    { id: "da-power-bi", kind: "subtopic", label: "Power BI",
      description: "Incorporate data models, configure table relations, and design corporate reporting interfaces.",
      links: [{ title: "Microsoft Power BI Docs", url: "https://learn.microsoft.com/en-us/power-bi/" }],
      position: { x: 380, y: 495 } },
    { id: "da-matplotlib-seaborn", kind: "subtopic", label: "Matplotlib/Seaborn",
      description: "Generate scatter plots, distributions, heatmaps, and line charts programmatically inside Python.",
      links: [{ title: "Seaborn Documentation", url: "https://seaborn.pydata.org/" }],
      position: { x: 380, y: 550 } },

    // 4. Analysis Techniques
    { id: "da-analysis-techniques", kind: "milestone", label: "Analysis Techniques",
      description: "Apply statistical testing and regression models to extract actionable business insights.",
      position: { x: 60, y: 660 } },
    { id: "da-ab-testing", kind: "subtopic", label: "A/B Testing",
      description: "Determine statistical significance between control and variant interface designs or features.",
      links: [{ title: "Harvard A/B Testing Guide", url: "https://hbr.org/2017/06/a-refresher-on-ab-testing" }],
      position: { x: 380, y: 660 } },
    { id: "da-regression-analysis", kind: "subtopic", label: "Regression Analysis",
      description: "Model relationship equations between dependent and independent data variables.",
      links: [{ title: "Scikit-Learn Linear Models", url: "https://scikit-learn.org/stable/modules/linear_model.html" }],
      position: { x: 380, y: 715 } },
    { id: "da-cohort-analysis", kind: "subtopic", label: "Cohort Analysis",
      description: "Examine behavioral trends of specific user groups grouped by shared transaction dates.",
      links: [{ title: "Optimizely Cohort Guide", url: "https://www.optimizely.com/optimization-glossary/cohort-analysis/" }],
      position: { x: 380, y: 770 } },

    // 5. Communication
    { id: "da-communication", kind: "milestone", label: "Communication",
      description: "Synthesize findings into executive reporting documents and data narratives.",
      position: { x: 60, y: 880 } },
    { id: "da-dashboards", kind: "subtopic", label: "Dashboards",
      description: "Synthesize critical operational metrics into real-time visual grid control boards.",
      links: [{ title: "Google Looker Studio", url: "https://lookerstudio.google.com/" }],
      position: { x: 380, y: 880 } },
    { id: "da-storytelling", kind: "subtopic", label: "Storytelling with Data",
      description: "Structure reports around clear questions, context settings, evidence slides, and next steps.",
      links: [{ title: "Storytelling with Data Book", url: "https://www.storytellingwithdata.com/" }],
      position: { x: 380, y: 935 } },
    { id: "da-reporting", kind: "subtopic", label: "Reporting",
      description: "Write executive summaries and action items targeted at technical and non-technical partners.",
      links: [{ title: "Harvard Business Writing", url: "https://hbr.org/topic/business-writing" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-da-foundations-da-data-manipulation", source: "da-foundations", target: "da-data-manipulation" },
    { id: "e-da-data-manipulation-da-visualization", source: "da-data-manipulation", target: "da-visualization" },
    { id: "e-da-visualization-da-analysis-techniques", source: "da-visualization", target: "da-analysis-techniques" },
    { id: "e-da-analysis-techniques-da-communication", source: "da-analysis-techniques", target: "da-communication" },
  ],
};
