import { TaskflowContent } from "./types";

export const devopsTaskflow: TaskflowContent = {
  slug: "devops",
  title: "DevOps",
  nodes: [
    // 1. Operating Systems
    { id: "os", kind: "milestone", label: "Operating Systems",
      description: "Understand basic operating system concepts, process flows, and Linux network baselines.",
      position: { x: 60, y: 0 } },
    { id: "os-linux", kind: "subtopic", label: "Linux Basics",
      description: "Learn fundamental terminal commands, directory navigation, file permissions, and user controls in Linux.",
      links: [{ title: "Linux Foundation Docs", url: "https://www.linuxfoundation.org/" }],
      position: { x: 380, y: 0 } },
    { id: "os-process", kind: "subtopic", label: "Process Management",
      description: "Understand how processes are spawned, monitored, backgrounded, and terminated in modern operating systems.",
      links: [{ title: "Linux Process Guide", url: "https://tldp.org/LDP/lpg/" }],
      position: { x: 380, y: 55 } },
    { id: "os-net", kind: "subtopic", label: "Networking Basics",
      description: "Get familiar with ports, protocol stacks (TCP/UDP, HTTP), IP routing, and DNS records.",
      links: [{ title: "Network Troubleshooting Guide", url: "https://www.netacad.com/" }],
      position: { x: 380, y: 110 } },

    // 2. Version Control
    { id: "vcs", kind: "milestone", label: "Version Control",
      description: "Manage repository version files and branching configurations.",
      position: { x: 60, y: 220 } },
    { id: "vcs-git", kind: "subtopic", label: "Git",
      description: "Use Git to save changes, rollback commits, resolve merge conflicts, and manage feature revisions.",
      links: [{ title: "Git Docs", url: "https://git-scm.com/doc" }],
      position: { x: 380, y: 220 } },
    { id: "vcs-trunk", kind: "subtopic", label: "Trunk-Based Development",
      description: "An optimization practice where developers merge frequent, small changes into a core branch to prevent merge fatigue.",
      links: [{ title: "Trunk Based Development Guide", url: "https://trunkbaseddevelopment.com/" }],
      position: { x: 380, y: 275 } },

    // 3. Scripting
    { id: "scripting", kind: "milestone", label: "Scripting",
      description: "Automate server maintenance, backup processes, and configuration operations.",
      position: { x: 60, y: 440 } },
    { id: "script-bash", kind: "subtopic", label: "Bash",
      description: "Write shell scripts to run native CLI operations sequentially.",
      links: [{ title: "GNU Bash manual", url: "https://www.gnu.org/software/bash/manual/" }],
      position: { x: 380, y: 440 } },
    { id: "script-python", kind: "subtopic", label: "Python",
      description: "Use Python for writing robust, cross-platform server scripts and automation engines.",
      links: [{ title: "Python Documentation", url: "https://docs.python.org/3/" }],
      position: { x: 380, y: 495 } },

    // 4. CI/CD
    { id: "cicd", kind: "milestone", label: "CI/CD",
      description: "Build and deploy application packages automatically upon repo updates.",
      position: { x: 60, y: 660 } },
    { id: "cicd-gha", kind: "subtopic", label: "GitHub Actions",
      description: "Configure automated workflows, build tests, and trigger cloud builds natively on GitHub repositories.",
      links: [{ title: "GitHub Actions docs", url: "https://docs.github.com/en/actions" }],
      position: { x: 380, y: 660 } },
    { id: "cicd-jenkins", kind: "subtopic", label: "Jenkins",
      description: "An open-source extensible automation server widely used for custom CI/CD pipelines.",
      links: [{ title: "Jenkins Website", url: "https://www.jenkins.io/" }],
      position: { x: 380, y: 715 } },

    // 5. Containers
    { id: "containers", kind: "milestone", label: "Containers",
      description: "Isolate software environments to run identically from dev to production systems.",
      position: { x: 60, y: 880 } },
    { id: "cont-docker", kind: "subtopic", label: "Docker",
      description: "Build and containerize systems using Dockerfiles and container layers.",
      links: [{ title: "Docker Docs", url: "https://docs.docker.com/" }],
      position: { x: 380, y: 880 } },
    { id: "cont-registries", kind: "subtopic", label: "Container Registries",
      description: "Host build image packages on platforms like Docker Hub or GitHub Container Registry (GHCR).",
      links: [{ title: "Docker Hub Website", url: "https://hub.docker.com/" }],
      position: { x: 380, y: 935 } },

    // 6. Orchestration
    { id: "orchestration", kind: "milestone", label: "Orchestration",
      description: "Manage clusters, auto-scaling groups, and multi-container lifecycle nodes in production.",
      position: { x: 60, y: 1100 } },
    { id: "orch-k8s", kind: "subtopic", label: "Kubernetes",
      description: "An open-source system developed by Google to automate deployment, scaling, and cluster management of containers.",
      links: [{ title: "Kubernetes Website", url: "https://kubernetes.io/" }],
      position: { x: 380, y: 1100 } },
    { id: "orch-helm", kind: "subtopic", label: "Helm",
      description: "The package manager for Kubernetes to deploy, update, and manage templated k8s charts.",
      links: [{ title: "Helm Website", url: "https://helm.sh/" }],
      position: { x: 380, y: 1155 } },

    // 7. Infrastructure as Code
    { id: "iac", kind: "milestone", label: "Infrastructure as Code",
      description: "Provision cloud infrastructure and coordinate server states using configuration code files.",
      position: { x: 60, y: 1320 } },
    { id: "iac-terraform", kind: "subtopic", label: "Terraform",
      description: "An open-source tool by HashiCorp to build, change, and version cloud infrastructure safely via declarative files.",
      links: [{ title: "Terraform Website", url: "https://www.terraform.io/" }],
      position: { x: 380, y: 1320 } },
    { id: "iac-ansible", kind: "subtopic", label: "Ansible",
      description: "An agentless configuration management engine to automate server configurations and deployments.",
      links: [{ title: "Ansible Website", url: "https://www.ansible.com/" }],
      position: { x: 380, y: 1375 } },

    // 8. Monitoring
    { id: "monitoring", kind: "milestone", label: "Monitoring",
      description: "Track system health metrics, analyze log anomalies, and trigger alerting metrics.",
      position: { x: 60, y: 1540 } },
    { id: "mon-prometheus", kind: "subtopic", label: "Prometheus",
      description: "An open-source system monitoring and alerting toolkit designed around time-series databases.",
      links: [{ title: "Prometheus Website", url: "https://prometheus.io/" }],
      position: { x: 380, y: 1540 } },
    { id: "mon-grafana", kind: "subtopic", label: "Grafana",
      description: "An open-source visualization tool to run search queries and render metric analytics dashboards.",
      links: [{ title: "Grafana Website", url: "https://grafana.com/" }],
      position: { x: 380, y: 1595 } },
  ],
  edges: [
    { id: "e-os-vcs", source: "os", target: "vcs" },
    { id: "e-vcs-script", source: "vcs", target: "scripting" },
    { id: "e-script-cicd", source: "scripting", target: "cicd" },
    { id: "e-cicd-cont", source: "cicd", target: "containers" },
    { id: "e-cont-orch", source: "containers", target: "orchestration" },
    { id: "e-orch-iac", source: "orchestration", target: "iac" },
    { id: "e-iac-mon", source: "iac", target: "monitoring" },
  ],
};
