import { TaskflowContent } from "./types";

export const devrelTaskflow: TaskflowContent = {
  slug: "devrel",
  title: "Developer Relations",
  nodes: [
    // 1. Foundations
    { id: "foundations", kind: "milestone", label: "Foundations",
      description: "Learn core communication skills required to represent software platforms to developers.",
      position: { x: 60, y: 0 } },
    { id: "dev-tech-writing", kind: "subtopic", label: "Technical Writing",
      description: "Write clear, concise technical documents, tutorials, and configuration summaries.",
      links: [{ title: "Google Technical Writing Course", url: "https://developers.google.com/tech-writing" }],
      position: { x: 380, y: 0 } },
    { id: "dev-public-speaking", kind: "subtopic", label: "Public Speaking",
      description: "Present complex technical concepts clearly to user audiences at conferences and meetups.",
      links: [{ title: "Toastmasters International", url: "https://www.toastmasters.org/" }],
      position: { x: 380, y: 55 } },
    { id: "dev-community-building", kind: "subtopic", label: "Community Building",
      description: "Build, moderate, and sustain groups of software developers around products.",
      links: [{ title: "Community Roundtable", url: "https://thecommunityroundtable.com/" }],
      position: { x: 380, y: 110 } },

    // 2. Content Creation
    { id: "content-creation", kind: "milestone", label: "Content Creation",
      description: "Develop instructional content to educate developers on how to use APIs and tools.",
      position: { x: 60, y: 220 } },
    { id: "dev-blogging", kind: "subtopic", label: "Blogging",
      description: "Author educational articles explaining engineering solutions and updates.",
      links: [{ title: "Dev.to Community", url: "https://dev.to/" }],
      position: { x: 380, y: 220 } },
    { id: "dev-video-tutorials", kind: "subtopic", label: "Video Tutorials",
      description: "Record video walk-throughs demonstrating tools and integration steps.",
      links: [{ title: "YouTube Creators Info", url: "https://www.youtube.com/creators/" }],
      position: { x: 380, y: 275 } },
    { id: "dev-documentation", kind: "subtopic", label: "Documentation",
      description: "Design structured, accessible api references and onboarding guides.",
      links: [{ title: "Write the Docs Community", url: "https://www.writethedocs.org/" }],
      position: { x: 380, y: 330 } },

    // 3. Developer Tools
    { id: "developer-tools", kind: "milestone", label: "Developer Tools",
      description: "Build assets that lower the barrier to entry for developer integrations.",
      position: { x: 60, y: 440 } },
    { id: "dev-sdks-apis", kind: "subtopic", label: "SDKs & APIs",
      description: "Design developer SDK wrappers and clean HTTP endpoints.",
      links: [{ title: "APIMatic SDK Design", url: "https://www.apimatic.io/" }],
      position: { x: 380, y: 440 } },
    { id: "dev-sample-apps", kind: "subtopic", label: "Sample Apps",
      description: "Build complete demonstration apps that illustrate production integration architectures.",
      links: [{ title: "GitHub Explore Sample Projects", url: "https://github.com/explore" }],
      position: { x: 380, y: 495 } },
    { id: "dev-code-examples", kind: "subtopic", label: "Code Examples",
      description: "Write short snippet blocks solving discrete tasks inside api guides.",
      links: [{ title: "StackOverflow Developer Info", url: "https://stackoverflow.com/" }],
      position: { x: 380, y: 550 } },

    // 4. Community Engagement
    { id: "community-engagement", kind: "milestone", label: "Community Engagement",
      description: "Interact directly with users where they naturally gather to gather feedback and assist.",
      position: { x: 60, y: 660 } },
    { id: "dev-discord-slack", kind: "subtopic", label: "Discord/Slack",
      description: "Create, moderate, and engage with users inside chat channels.",
      links: [{ title: "Discord Developers Homepage", url: "https://discord.com/developers/active-developer" }],
      position: { x: 380, y: 660 } },
    { id: "dev-conferences", kind: "subtopic", label: "Conferences",
      description: "Attend developer conventions, run workshops, and staff booths.",
      links: [{ title: "DevRelCon Conference Website", url: "https://developerrelations.com/" }],
      position: { x: 380, y: 715 } },
    { id: "dev-open-source", kind: "subtopic", label: "Open Source Contributions",
      description: "Contribute to open repositories to support developer software ecosystems.",
      links: [{ title: "Open Source Guide", url: "https://opensource.guide/" }],
      position: { x: 380, y: 770 } },

    // 5. Metrics & Feedback
    { id: "metrics-feedback", kind: "milestone", label: "Metrics & Feedback",
      description: "Measure DevRel program value and funnel developer feedback back to product teams.",
      position: { x: 60, y: 880 } },
    { id: "dev-surveys", kind: "subtopic", label: "Developer Surveys",
      description: "Conduct user surveys to understand paint points and track developer satisfaction levels.",
      links: [{ title: "StackOverflow Developer Survey", url: "https://survey.stackoverflow.co/" }],
      position: { x: 380, y: 880 } },
    { id: "dev-analytics", kind: "subtopic", label: "Analytics",
      description: "Track API signups, GitHub stargazers, pageviews, and community membership analytics.",
      links: [{ title: "Google Analytics Homepage", url: "https://analytics.google.com/" }],
      position: { x: 380, y: 935 } },
    { id: "dev-feedback-loops", kind: "subtopic", label: "Feedback Loops",
      description: "Synthesize developer issues into structured feature requests for core product engineers.",
      links: [{ title: "ProductBoard Product Management", url: "https://www.productboard.com/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-foundations-content-creation", source: "foundations", target: "content-creation" },
    { id: "e-content-creation-developer-tools", source: "content-creation", target: "developer-tools" },
    { id: "e-developer-tools-community-engagement", source: "developer-tools", target: "community-engagement" },
    { id: "e-community-engagement-metrics-feedback", source: "community-engagement", target: "metrics-feedback" },
  ],
};
