import { TaskflowContent } from "./types";

export const dockerTaskflow: TaskflowContent = {
  slug: "docker",
  title: "Docker",
  nodes: [
    // 1. Basics
    { id: "docker-basics", kind: "milestone", label: "Basics",
      description: "Learn how to build images, execute isolated containers, and configure container layers.",
      position: { x: 60, y: 0 } },
    { id: "docker-images-containers", kind: "subtopic", label: "Images & Containers",
      description: "Differentiate static read-only images from dynamic, writable container instances.",
      links: [{ title: "Docker Guides: Get Started", url: "https://docs.docker.com/get-started/docker-concepts/the-basics/" }],
      position: { x: 380, y: 0 } },
    { id: "docker-dockerfile", kind: "subtopic", label: "Dockerfile",
      description: "Write custom images recipes using commands like FROM, RUN, COPY, and CMD.",
      links: [{ title: "Dockerfile Reference Guide", url: "https://docs.docker.com/reference/dockerfile/" }],
      position: { x: 380, y: 55 } },
    { id: "docker-cli", kind: "subtopic", label: "Docker CLI",
      description: "Command container states via docker build, docker run, docker ps, and docker exec.",
      links: [{ title: "Docker CLI Commands Docs", url: "https://docs.docker.com/reference/cli/docker/" }],
      position: { x: 380, y: 110 } },

    // 2. Networking & Storage
    { id: "docker-networking-storage", kind: "milestone", label: "Networking & Storage",
      description: "Persist container data paths and configure virtual network links.",
      position: { x: 60, y: 220 } },
    { id: "docker-volumes", kind: "subtopic", label: "Volumes",
      description: "Persist databases and logs using dedicated storage volumes managed by Docker engine.",
      links: [{ title: "Docker Volumes Documentation", url: "https://docs.docker.com/storage/volumes/" }],
      position: { x: 380, y: 220 } },
    { id: "docker-bind-mounts", kind: "subtopic", label: "Bind Mounts",
      description: "Mount files from the host system directory directly into container targets for local hot-reload.",
      links: [{ title: "Docker Bind Mounts Guide", url: "https://docs.docker.com/storage/bind-mounts/" }],
      position: { x: 380, y: 275 } },
    { id: "docker-networks", kind: "subtopic", label: "Docker Networks",
      description: "Configure communications using bridge, host, overlay, or custom network driver protocols.",
      links: [{ title: "Docker Network Overview", url: "https://docs.docker.com/network/" }],
      position: { x: 380, y: 330 } },

    // 3. Compose
    { id: "docker-compose", kind: "milestone", label: "Compose",
      description: "Orchestrate multi-container applications easily using yaml configuration templates.",
      position: { x: 60, y: 440 } },
    { id: "docker-compose-yml", kind: "subtopic", label: "docker-compose.yml",
      description: "Define multi-container service stacks, network mappings, and storage configs inside a single file.",
      links: [{ title: "Docker Compose Specification", url: "https://docs.docker.com/compose/compose-file/" }],
      position: { x: 380, y: 440 } },
    { id: "docker-multi-container", kind: "subtopic", label: "Multi-container Apps",
      description: "Launch linked services like database containers, cache systems, and API servers together.",
      links: [{ title: "Docker Compose Overview", url: "https://docs.docker.com/compose/" }],
      position: { x: 380, y: 495 } },
    { id: "docker-env-variables", kind: "subtopic", label: "Environment Variables",
      description: "Pass run parameters and database keys safely into services utilizing dotenv mappings.",
      links: [{ title: "Docker Compose Environment Variables", url: "https://docs.docker.com/compose/environment-variables/" }],
      position: { x: 380, y: 550 } },

    // 4. Optimization
    { id: "docker-optimization", kind: "milestone", label: "Optimization",
      description: "Speed up image compiles, scale down output sizes, and configure build cache paths.",
      position: { x: 60, y: 660 } },
    { id: "docker-multi-stage-builds", kind: "subtopic", label: "Multi-stage Builds",
      description: "Separate compilation environments from final runtimes to output small, minimal images.",
      links: [{ title: "Docker Multi-stage Builds Guide", url: "https://docs.docker.com/build/building/multi-stage/" }],
      position: { x: 380, y: 660 } },
    { id: "docker-image-size-reduction", kind: "subtopic", label: "Image Size Reduction",
      description: "Minimize image layers using lightweight Alpine distros, removing unnecessary packages.",
      links: [{ title: "Docker Build Optimization Tips", url: "https://docs.docker.com/build/cache/" }],
      position: { x: 380, y: 715 } },
    { id: "docker-caching-layers", kind: "subtopic", label: "Caching Layers",
      description: "Order Dockerfile commands to maximize build-cache hits and speed up continuous integration builds.",
      links: [{ title: "Docker Cache Allocation", url: "https://docs.docker.com/build/cache/garbage-collection/" }],
      position: { x: 380, y: 770 } },

    // 5. Production
    { id: "docker-production", kind: "milestone", label: "Production",
      description: "Distribute images, add health verification rules, and analyze image vulnerabilities.",
      position: { x: 60, y: 880 } },
    { id: "docker-registries", kind: "subtopic", label: "Docker Registries",
      description: "Upload and download images using standard services like Docker Hub or AWS ECR.",
      links: [{ title: "Docker Hub Registry Docs", url: "https://docs.docker.com/docker-hub/" }],
      position: { x: 380, y: 880 } },
    { id: "docker-health-checks", kind: "subtopic", label: "Health Checks",
      description: "Declare HEALTHCHECK checks in Dockerfiles to verify container internal service states.",
      links: [{ title: "Docker Reference: HEALTHCHECK Instruction", url: "https://docs.docker.com/reference/dockerfile/#healthcheck" }],
      position: { x: 380, y: 935 } },
    { id: "docker-security-scanning", kind: "subtopic", label: "Security Scanning",
      description: "Scan images for package vulnerabilities and run containers using restricted user roles.",
      links: [{ title: "Docker Scout Overview", url: "https://docs.docker.com/scout/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-docker-basics-docker-networking-storage", source: "docker-basics", target: "docker-networking-storage" },
    { id: "e-docker-networking-storage-docker-compose", source: "docker-networking-storage", target: "docker-compose" },
    { id: "e-docker-compose-docker-optimization", source: "docker-compose", target: "docker-optimization" },
    { id: "e-docker-optimization-docker-production", source: "docker-optimization", target: "docker-production" },
  ],
};
