import { TaskflowContent } from "./types";

export const frontendTaskflow: TaskflowContent = {
  slug: "frontend",
  title: "Frontend",
  nodes: [
    // Internet
    { id: "internet", kind: "milestone", label: "Internet",
      description: "Foundational knowledge of how the internet works before diving into frontend development.",
      position: { x: 60, y: 0 } },
    { id: "internet-how-it-works", kind: "subtopic", label: "How does the internet work?",
      description: "Understand what happens when you type a URL into your browser, from DNS resolution to receiving a response.",
      links: [{ title: "MDN: How the Web works", url: "https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works" }],
      position: { x: 380, y: 0 } },
    { id: "internet-http", kind: "subtopic", label: "What is HTTP?",
      description: "Learn about the HTTP protocol, request/response cycle, methods, status codes and headers.",
      links: [{ title: "MDN: HTTP overview", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview" }],
      position: { x: 380, y: 55 } },
    { id: "internet-dns", kind: "subtopic", label: "DNS and how it works",
      description: "Learn how domain names get translated into IP addresses through the Domain Name System.",
      links: [{ title: "Cloudflare: What is DNS", url: "https://www.cloudflare.com/learning/dns/what-is-dns/" }],
      position: { x: 380, y: 110 } },
    { id: "internet-hosting", kind: "subtopic", label: "What is Hosting?",
      description: "Understand the basics of web hosting and how static and dynamic sites are served.",
      links: [{ title: "MDN: What is a web server", url: "https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server" }],
      position: { x: 380, y: 165 } },

    // HTML
    { id: "html", kind: "milestone", label: "HTML",
      description: "The markup language used to structure content on the web.",
      position: { x: 60, y: 220 } },
    { id: "html-basics", kind: "subtopic", label: "Learn the basics",
      description: "Get familiar with HTML tags, elements, attributes and basic document structure.",
      links: [{ title: "MDN: HTML basics", url: "https://developer.mozilla.org/en-US/docs/Learn/HTML" }],
      position: { x: 380, y: 220 } },
    { id: "html-semantic", kind: "subtopic", label: "Writing Semantic HTML",
      description: "Use HTML elements according to their intended meaning to build accessible, well-structured pages.",
      links: [{ title: "MDN: HTML semantics", url: "https://developer.mozilla.org/en-US/docs/Glossary/Semantics" }],
      position: { x: 380, y: 275 } },
    { id: "html-forms", kind: "subtopic", label: "Forms and Validations",
      description: "Learn how to build forms, use input types, and implement client-side validation.",
      links: [{ title: "MDN: Forms guide", url: "https://developer.mozilla.org/en-US/docs/Learn/Forms" }],
      position: { x: 380, y: 330 } },

    // CSS
    { id: "css", kind: "milestone", label: "CSS",
      description: "The language used to style and lay out web pages.",
      position: { x: 60, y: 440 } },
    { id: "css-basics", kind: "subtopic", label: "Learn the basics",
      description: "Understand selectors, the cascade, specificity, and how to apply styles to HTML.",
      links: [{ title: "MDN: CSS basics", url: "https://developer.mozilla.org/en-US/docs/Learn/CSS" }],
      position: { x: 380, y: 440 } },
    { id: "css-flexbox", kind: "subtopic", label: "Flexbox",
      description: "Learn the flexible box layout model for arranging items in rows or columns.",
      links: [{ title: "CSS-Tricks: Guide to Flexbox", url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/" }],
      position: { x: 380, y: 495 } },
    { id: "css-grid", kind: "subtopic", label: "CSS Grid",
      description: "Learn the grid layout system for building two-dimensional page layouts.",
      links: [{ title: "CSS-Tricks: Complete Guide to Grid", url: "https://css-tricks.com/snippets/css/complete-guide-grid/" }],
      position: { x: 380, y: 550 } },

    // JavaScript
    { id: "javascript", kind: "milestone", label: "JavaScript",
      description: "The programming language that powers interactivity on the web.",
      position: { x: 60, y: 660 } },
    { id: "js-basics", kind: "subtopic", label: "Learn the basics",
      description: "Variables, data types, functions, conditionals, loops and operators.",
      links: [{ title: "MDN: JavaScript first steps", url: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps" }],
      position: { x: 380, y: 660 } },
    { id: "js-dom", kind: "subtopic", label: "DOM Manipulation",
      description: "Learn how to select, traverse, and update elements on a page using JavaScript.",
      links: [{ title: "MDN: Manipulating documents", url: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents" }],
      position: { x: 380, y: 715 } },
    { id: "js-fetch", kind: "subtopic", label: "Fetch API",
      description: "Learn how to make HTTP requests from the browser using the Fetch API and handle responses.",
      links: [{ title: "MDN: Using Fetch", url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch" }],
      position: { x: 380, y: 770 } },
    { id: "js-es6", kind: "subtopic", label: "ES6+ Features",
      description: "Arrow functions, destructuring, spread/rest, template literals, async/await and modules.",
      links: [{ title: "MDN: JavaScript Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide" }],
      position: { x: 380, y: 825 } },

    // Package Managers
    { id: "package-managers", kind: "milestone", label: "Package Managers",
      description: "Tools for installing and managing project dependencies.",
      position: { x: 60, y: 880 } },
    { id: "pm-npm", kind: "subtopic", label: "npm",
      description: "The default package manager for Node.js, used to install and manage dependencies.",
      links: [{ title: "npm docs", url: "https://docs.npmjs.com/" }],
      position: { x: 380, y: 880 } },
    { id: "pm-pnpm", kind: "subtopic", label: "pnpm",
      description: "A fast, disk space efficient alternative to npm with strict dependency resolution.",
      links: [{ title: "pnpm docs", url: "https://pnpm.io/motivation" }],
      position: { x: 380, y: 935 } },

    // Frameworks
    { id: "frameworks", kind: "milestone", label: "Pick a Framework",
      description: "Modern UI libraries and frameworks for building component-based interfaces.",
      position: { x: 60, y: 1100 } },
    { id: "fw-react", kind: "subtopic", label: "React",
      description: "A component-based library for building user interfaces, maintained by Meta.",
      links: [{ title: "React docs", url: "https://react.dev/" }],
      position: { x: 380, y: 1100 } },
    { id: "fw-vue", kind: "subtopic", label: "Vue.js",
      description: "An approachable, performant framework for building UIs with a gentle learning curve.",
      links: [{ title: "Vue docs", url: "https://vuejs.org/" }],
      position: { x: 380, y: 1155 } },
    { id: "fw-svelte", kind: "subtopic", label: "Svelte",
      description: "A compiler-based framework that shifts work from runtime to build time for highly efficient apps.",
      links: [{ title: "Svelte docs", url: "https://svelte.dev/" }],
      position: { x: 380, y: 1210 } },

    // Build Tools
    { id: "build-tools", kind: "milestone", label: "Build Tools",
      description: "Tooling for bundling, transpiling and optimizing frontend code.",
      position: { x: 60, y: 1320 } },
    { id: "bt-vite", kind: "subtopic", label: "Vite",
      description: "A fast frontend build tool and dev server with instant hot module replacement.",
      links: [{ title: "Vite docs", url: "https://vitejs.dev/" }],
      position: { x: 380, y: 1320 } },
    { id: "bt-eslint", kind: "subtopic", label: "ESLint",
      description: "A static analysis tool for identifying and fixing problems in JavaScript/TypeScript code.",
      links: [{ title: "ESLint docs", url: "https://eslint.org/" }],
      position: { x: 380, y: 1375 } },

    // Testing
    { id: "testing", kind: "milestone", label: "Testing",
      description: "Practices and tools for verifying that frontend code works correctly.",
      position: { x: 60, y: 1540 } },
    { id: "test-unit", kind: "subtopic", label: "Unit Testing",
      description: "Write isolated tests for individual functions and components using tools like Vitest or Jest.",
      links: [{ title: "Vitest docs", url: "https://vitest.dev/" }],
      position: { x: 380, y: 1540 } },
    { id: "test-e2e", kind: "subtopic", label: "End-to-End Testing",
      description: "Test full user flows in a real browser environment using tools like Playwright or Cypress.",
      links: [{ title: "Playwright docs", url: "https://playwright.dev/" }],
      position: { x: 380, y: 1595 } },
  ],
  edges: [
    { id: "e-internet-html", source: "internet", target: "html" },
    { id: "e-html-css", source: "html", target: "css" },
    { id: "e-css-js", source: "css", target: "javascript" },
    { id: "e-js-pm", source: "javascript", target: "package-managers" },
    { id: "e-pm-fw", source: "package-managers", target: "frameworks" },
    { id: "e-pm-fw-bt", source: "frameworks", target: "build-tools" },
    { id: "e-bt-test", source: "build-tools", target: "testing" },
  ],
};
