import { TaskflowContent } from "./types";

export const fullStackTaskflow: TaskflowContent = {
  slug: "full-stack",
  title: "Full Stack",
  nodes: [
    // 1. Frontend Fundamentals
    { id: "frontend-fundamentals", kind: "milestone", label: "Frontend Fundamentals",
      description: "Learn the core markup, styling, and programming languages that build all web client interfaces.",
      position: { x: 60, y: 0 } },
    { id: "fs-html", kind: "subtopic", label: "HTML",
      description: "HyperText Markup Language shapes the structural layout of web content.",
      links: [{ title: "MDN HTML Guide", url: "https://developer.mozilla.org/en-US/docs/Web/HTML" }],
      position: { x: 380, y: 0 } },
    { id: "fs-css", kind: "subtopic", label: "CSS",
      description: "Cascading Style Sheets manage colors, grid alignments, fonts, and responsive behaviors.",
      links: [{ title: "MDN CSS Guide", url: "https://developer.mozilla.org/en-US/docs/Web/CSS" }],
      position: { x: 380, y: 55 } },
    { id: "fs-javascript", kind: "subtopic", label: "JavaScript",
      description: "The core programming language that adds functional dynamics and server query handling to web components.",
      links: [{ title: "MDN JavaScript Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" }],
      position: { x: 380, y: 110 } },

    // 2. Backend Fundamentals
    { id: "backend-fundamentals", kind: "milestone", label: "Backend Fundamentals",
      description: "Understand server runtime setups, data storage designs, and query parameters.",
      position: { x: 60, y: 220 } },
    { id: "fs-nodejs", kind: "subtopic", label: "Node.js",
      description: "A server-side JavaScript runtime environment built on Chrome's V8 engine.",
      links: [{ title: "Node.js Website", url: "https://nodejs.org/" }],
      position: { x: 380, y: 220 } },
    { id: "fs-databases", kind: "subtopic", label: "Databases",
      description: "Store, retrieve, query, and manage application state in SQL or NoSQL databases.",
      links: [{ title: "PostgreSQL Website", url: "https://www.postgresql.org/" }],
      position: { x: 380, y: 275 } },
    { id: "fs-rest-apis", kind: "subtopic", label: "REST APIs",
      description: "Build client-server endpoints using REST conventions, HTTP response codes, and data formats.",
      links: [{ title: "REST API Tutorial", url: "https://restfulapi.net/" }],
      position: { x: 380, y: 330 } },

    // 3. Pick a Frontend Framework
    { id: "frontend-framework", kind: "milestone", label: "Pick a Frontend Framework",
      description: "Use modern component libraries to build scalable, reactive web client applications.",
      position: { x: 60, y: 440 } },
    { id: "fs-react", kind: "subtopic", label: "React",
      description: "A declarative, component-based user interface library maintained by Meta.",
      links: [{ title: "React Website", url: "https://react.dev/" }],
      position: { x: 380, y: 440 } },
    { id: "fs-vue", kind: "subtopic", label: "Vue",
      description: "An approachable, flexible, and feature-rich user interface framework.",
      links: [{ title: "Vue.js Website", url: "https://vuejs.org/" }],
      position: { x: 380, y: 495 } },
    { id: "fs-angular", kind: "subtopic", label: "Angular",
      description: "A robust, type-safe development platform for building large scale applications.",
      links: [{ title: "Angular Website", url: "https://angular.dev/" }],
      position: { x: 380, y: 550 } },

    // 4. Pick a Backend Framework
    { id: "backend-framework", kind: "milestone", label: "Pick a Backend Framework",
      description: "Use server-side framework engines to expedite logic, database queries, and endpoint routing.",
      position: { x: 60, y: 660 } },
    { id: "fs-express", kind: "subtopic", label: "Express",
      description: "A minimal and flexible web application framework for Node.js backend servers.",
      links: [{ title: "Express Docs", url: "https://expressjs.com/" }],
      position: { x: 380, y: 660 } },
    { id: "fs-django", kind: "subtopic", label: "Django",
      description: "A high-level Python web framework that encourages rapid design and clean pragmatics.",
      links: [{ title: "Django Project Website", url: "https://www.djangoproject.com/" }],
      position: { x: 380, y: 715 } },
    { id: "fs-springboot", kind: "subtopic", label: "Spring Boot",
      description: "A Java-based framework designed to simplify creation of stand-alone, production-grade Spring servers.",
      links: [{ title: "Spring Boot Docs", url: "https://spring.io/projects/spring-boot" }],
      position: { x: 380, y: 770 } },

    // 5. Deployment
    { id: "deployment", kind: "milestone", label: "Deployment",
      description: "Move build files to cloud hostings, orchestrating deployment runs automatically.",
      position: { x: 60, y: 880 } },
    { id: "fs-docker", kind: "subtopic", label: "Docker",
      description: "Bundle code configurations and engine dependencies into lightweight, isolated containers.",
      links: [{ title: "Docker Website", url: "https://www.docker.com/" }],
      position: { x: 380, y: 880 } },
    { id: "fs-cicd", kind: "subtopic", label: "CI/CD",
      description: "Build and deploy application packages automatically upon repository commits.",
      links: [{ title: "GitHub Actions Docs", url: "https://docs.github.com/en/actions" }],
      position: { x: 380, y: 935 } },
    { id: "fs-cloud-hosting", kind: "subtopic", label: "Cloud Hosting",
      description: "Host web client scripts and server runtimes on cloud services like AWS, Vercel, or Heroku.",
      links: [{ title: "Vercel Website", url: "https://vercel.com/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-frontend-fundamentals-backend-fundamentals", source: "frontend-fundamentals", target: "backend-fundamentals" },
    { id: "e-backend-fundamentals-frontend-framework", source: "backend-fundamentals", target: "frontend-framework" },
    { id: "e-frontend-framework-backend-framework", source: "frontend-framework", target: "backend-framework" },
    { id: "e-backend-framework-deployment", source: "backend-framework", target: "deployment" },
  ],
};
