import { TaskflowContent } from "./types";

export const golangTaskflow: TaskflowContent = {
  slug: "golang",
  title: "Go",
  nodes: [
    // 1. Basics
    { id: "go-basics", kind: "milestone", label: "Basics",
      description: "Learn Go variables declarations, basic syntax structures, and compile processes.",
      position: { x: 60, y: 0 } },
    { id: "go-syntax-variables", kind: "subtopic", label: "Syntax & Variables",
      description: "Declare package imports, use short variable declaration syntax (:=), and configure main entry points.",
      links: [{ title: "A Tour of Go: Packages, variables, and functions", url: "https://go.dev/tour/flowcontrol/1" }],
      position: { x: 380, y: 0 } },
    { id: "go-functions", kind: "subtopic", label: "Functions",
      description: "Accept input arguments, return multiple output variables, and handle named return values.",
      links: [{ title: "A Tour of Go: Functions", url: "https://go.dev/tour/basics/4" }],
      position: { x: 380, y: 55 } },
    { id: "go-control-flow", kind: "subtopic", label: "Control Flow",
      description: "Direct decisions using standard if checks, write compact switch blocks, and repeat actions with for loops.",
      links: [{ title: "A Tour of Go: Flow Control Statements", url: "https://go.dev/tour/flowcontrol/1" }],
      position: { x: 380, y: 110 } },

    // 2. Data Structures
    { id: "go-data-structures", kind: "milestone", label: "Data Structures",
      description: "Understand static array parameters, dynamically resizing slices, dictionaries, and custom shapes.",
      position: { x: 60, y: 220 } },
    { id: "go-arrays-slices", kind: "subtopic", label: "Arrays & Slices",
      description: "Allocate fixed arrays or manipulate dynamic, high-performance slices of arrays.",
      links: [{ title: "Go Slices: usage and internals", url: "https://go.dev/blog/slices-intro" }],
      position: { x: 380, y: 220 } },
    { id: "go-maps", kind: "subtopic", label: "Maps",
      description: "Configure key-value dictionary mappings to store and read values efficiently.",
      links: [{ title: "Go Maps in Action", url: "https://go.dev/blog/maps" }],
      position: { x: 380, y: 275 } },
    { id: "go-structs", kind: "subtopic", label: "Structs",
      description: "Define object record shapes, group attributes, and compose models without class inheritance.",
      links: [{ title: "A Tour of Go: Structs", url: "https://go.dev/tour/moretypes/2" }],
      position: { x: 380, y: 330 } },

    // 3. Concurrency
    { id: "go-concurrency", kind: "milestone", label: "Concurrency",
      description: "Execute concurrent subroutines, pipe data across threads, and coordinate locks.",
      position: { x: 60, y: 440 } },
    { id: "go-goroutines", kind: "subtopic", label: "Goroutines",
      description: "Execute lightweight thread subroutines managed by Go runtime using the go keyword.",
      links: [{ title: "A Tour of Go: Goroutines", url: "https://go.dev/tour/concurrency/1" }],
      position: { x: 380, y: 440 } },
    { id: "go-channels", kind: "subtopic", label: "Channels",
      description: "Pipe data values safely across running goroutines to prevent data races.",
      links: [{ title: "A Tour of Go: Channels", url: "https://go.dev/tour/concurrency/2" }],
      position: { x: 380, y: 495 } },
    { id: "go-sync-package", kind: "subtopic", label: "sync Package",
      description: "Coordinate goroutines executions using sync.WaitGroup blocks and mutual exclusion locks (sync.Mutex).",
      links: [{ title: "Go Standard Library: sync", url: "https://pkg.go.dev/sync" }],
      position: { x: 380, y: 550 } },

    // 4. Error Handling
    { id: "go-error-handling", kind: "milestone", label: "Error Handling",
      description: "Inspect returned error codes explicitly, recover from panics, and define custom error interfaces.",
      position: { x: 60, y: 660 } },
    { id: "go-error-interfaces", kind: "subtopic", label: "Error Interfaces",
      description: "Examine errors returned as standard values, checking if err != nil in call sites.",
      links: [{ title: "Go Blog: Defer, Panic, and Recover", url: "https://go.dev/blog/defer-panic-and-recover" }],
      position: { x: 380, y: 660 } },
    { id: "go-panic-recover", kind: "subtopic", label: "Panic & Recover",
      description: "Trigger crash exceptions using panic, and capture runtime failures using defer and recover.",
      links: [{ title: "Go Blog: Error Handling and Go", url: "https://go.dev/blog/error-handling-and-go" }],
      position: { x: 380, y: 715 } },
    { id: "go-custom-errors", kind: "subtopic", label: "Custom Errors",
      description: "Implement the custom error interface to return specific metadata fields on database or network failures.",
      links: [{ title: "Go Package errors", url: "https://pkg.go.dev/errors" }],
      position: { x: 380, y: 770 } },

    // 5. Tooling
    { id: "go-tooling", kind: "milestone", label: "Tooling",
      description: "Manage package modules imports, execute test suites, and audit standard library tools.",
      position: { x: 60, y: 880 } },
    { id: "go-modules", kind: "subtopic", label: "Modules (go mod)",
      description: "Initialize module dependencies paths, import packages, and verify checksums in go.sum.",
      links: [{ title: "Go Modules Reference", url: "https://go.dev/ref/mod" }],
      position: { x: 380, y: 880 } },
    { id: "go-testing", kind: "subtopic", label: "Testing",
      description: "Write unit test scripts and benchmark functions using Go's built-in testing framework.",
      links: [{ title: "Go Package testing Docs", url: "https://pkg.go.dev/testing" }],
      position: { x: 380, y: 935 } },
    { id: "go-standard-library", kind: "subtopic", label: "Standard Library",
      description: "Operate standard network interfaces (net/http), string formatters (fmt), and data parsers (encoding/json).",
      links: [{ title: "Go Standard Library Packages", url: "https://pkg.go.dev/std" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-go-basics-go-data-structures", source: "go-basics", target: "go-data-structures" },
    { id: "e-go-data-structures-go-concurrency", source: "go-data-structures", target: "go-concurrency" },
    { id: "e-go-concurrency-go-error-handling", source: "go-concurrency", target: "go-error-handling" },
    { id: "e-go-error-handling-go-tooling", source: "go-error-handling", target: "go-tooling" },
  ],
};
