import { TaskflowContent } from "./types";

export const iosTaskflow: TaskflowContent = {
  slug: "ios",
  title: "iOS",
  nodes: [
    // 1. Language Choice
    { id: "language-choice", kind: "milestone", label: "Language Choice",
      description: "Pick an iOS language to compile native mobile architectures.",
      position: { x: 60, y: 0 } },
    { id: "ios-swift", kind: "subtopic", label: "Swift",
      description: "Apple's modern, type-safe programming language designed for swift development.",
      links: [{ title: "Swift Website", url: "https://www.swift.org/" }],
      position: { x: 380, y: 0 } },
    { id: "ios-objective-c", kind: "subtopic", label: "Objective-C",
      description: "Apple's legacy object-oriented C extension language, still present in older systems.",
      links: [{ title: "Apple Objective-C Docs", url: "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html" }],
      position: { x: 380, y: 55 } },

    // 2. iOS Basics
    { id: "ios-basics", kind: "milestone", label: "iOS Basics",
      description: "Understand user interface controls and visual layouts on Apple devices.",
      position: { x: 60, y: 220 } },
    { id: "ios-uikit", kind: "subtopic", label: "UIKit",
      description: "Apple's traditional event-driven framework for constructing native mobile layout components.",
      links: [{ title: "Apple UIKit Docs", url: "https://developer.apple.com/documentation/uikit" }],
      position: { x: 380, y: 220 } },
    { id: "ios-swiftui", kind: "subtopic", label: "SwiftUI",
      description: "Apple's modern declarative UI framework to structure native user screens with simple code.",
      links: [{ title: "Apple SwiftUI Docs", url: "https://developer.apple.com/xcode/swiftui/" }],
      position: { x: 380, y: 275 } },
    { id: "ios-storyboards", kind: "subtopic", label: "Storyboards",
      description: "Visual canvas templates to layout controllers and screen transitions in Xcode.",
      links: [{ title: "Apple Storyboard Guide", url: "https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/DesigningUserInterfaces.html" }],
      position: { x: 380, y: 330 } },

    // 3. App Architecture
    { id: "app-architecture", kind: "milestone", label: "App Architecture",
      description: "Implement design patterns to divide logic and UI updates properly.",
      position: { x: 60, y: 440 } },
    { id: "ios-mvvm", kind: "subtopic", label: "MVVM",
      description: "Model-View-ViewModel paradigm separation logic from direct storyboard elements.",
      links: [{ title: "iOS MVVM Guide", url: "https://developer.apple.com/documentation/swiftui/managing-model-data-in-your-app" }],
      position: { x: 380, y: 440 } },
    { id: "ios-combine", kind: "subtopic", label: "Combine",
      description: "Apple's reactive programming framework to customize publishers and observe values.",
      links: [{ title: "Apple Combine Docs", url: "https://developer.apple.com/documentation/combine" }],
      position: { x: 380, y: 495 } },
    { id: "ios-dependency-injection", kind: "subtopic", label: "Dependency Injection",
      description: "Inject classes and storage utilities dynamically to keep app components decoupled.",
      links: [{ title: "Swift DI Guide", url: "https://developer.apple.com/documentation/swift/dependency-injection" }],
      position: { x: 380, y: 550 } },

    // 4. Data & Networking
    { id: "data-networking", kind: "milestone", label: "Data & Networking",
      description: "Fetch web API resources and write persistent local database tables.",
      position: { x: 60, y: 660 } },
    { id: "ios-core-data", kind: "subtopic", label: "Core Data",
      description: "Apple's local object graph persistent framework to model sqlite files.",
      links: [{ title: "Apple Core Data Docs", url: "https://developer.apple.com/documentation/coredata" }],
      position: { x: 380, y: 660 } },
    { id: "ios-urlsession", kind: "subtopic", label: "URLSession",
      description: "Perform system HTTP queries to pull remote server data objects.",
      links: [{ title: "Apple URLSession Docs", url: "https://developer.apple.com/documentation/foundation/urlsession" }],
      position: { x: 380, y: 715 } },
    { id: "ios-codable", kind: "subtopic", label: "Codable",
      description: "A built-in swift protocol to decode and encode local structs to JSON variables.",
      links: [{ title: "Apple Codable Docs", url: "https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types" }],
      position: { x: 380, y: 770 } },

    // 5. Publishing
    { id: "publishing", kind: "milestone", label: "Publishing",
      description: "Test iOS code modules, prepare certificates, and build App Store packages.",
      position: { x: 60, y: 880 } },
    { id: "ios-xctest", kind: "subtopic", label: "XCTest",
      description: "Build unit and UI tests within Apple's testing framework.",
      links: [{ title: "Apple XCTest Docs", url: "https://developer.apple.com/documentation/xctest" }],
      position: { x: 380, y: 880 } },
    { id: "ios-app-store", kind: "subtopic", label: "App Store Guidelines",
      description: "Follow Apple guidelines to construct packages that pass reviewer checks.",
      links: [{ title: "App Store Review Guidelines", url: "https://developer.apple.com/app-store/review/guidelines/" }],
      position: { x: 380, y: 935 } },
    { id: "ios-testflight", kind: "subtopic", label: "TestFlight",
      description: "Distribute beta software builds to external testers before production release.",
      links: [{ title: "Apple TestFlight Docs", url: "https://developer.apple.com/testflight/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-language-choice-ios-basics", source: "language-choice", target: "ios-basics" },
    { id: "e-ios-basics-app-architecture", source: "ios-basics", target: "app-architecture" },
    { id: "e-app-architecture-data-networking", source: "app-architecture", target: "data-networking" },
    { id: "e-data-networking-publishing", source: "data-networking", target: "publishing" },
  ],
};
