import { TaskflowContent } from "./types";

export const javaTaskflow: TaskflowContent = {
  slug: "java",
  title: "Java",
  nodes: [
    // 1. Basics
    { id: "java-basics", kind: "milestone", label: "Basics",
      description: "Write compiler statements, manage main functions definitions, and instantiate simple objects classes.",
      position: { x: 60, y: 0 } },
    { id: "java-syntax-variables", kind: "subtopic", label: "Syntax & Variables",
      description: "Declare class file scopes, write static void main statements, and specify strict variable categories.",
      links: [{ title: "Oracle Java Tutorial: Language Basics", url: "https://docs.oracle.com/javase/tutorial/java/nutsandbolts/index.html" }],
      position: { x: 380, y: 0 } },
    { id: "java-oop-basics", kind: "subtopic", label: "OOP Basics",
      description: "Understand object blueprints, constructors functions, instance configurations, and data methods.",
      links: [{ title: "Oracle Java Tutorial: OOP Concepts", url: "https://docs.oracle.com/javase/tutorial/java/concepts/index.html" }],
      position: { x: 380, y: 55 } },
    { id: "java-methods", kind: "subtopic", label: "Methods",
      description: "Declare parameter types, overload method names, and constrain class return parameters.",
      links: [{ title: "Oracle Java Tutorial: Defining Methods", url: "https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html" }],
      position: { x: 380, y: 110 } },

    // 2. Core Concepts
    { id: "java-core-concepts", kind: "milestone", label: "Core Concepts",
      description: "Define object contract interfaces, catch runtime errors, and navigate lists structures.",
      position: { x: 60, y: 220 } },
    { id: "java-interfaces-abstract", kind: "subtopic", label: "Interfaces & Abstract Classes",
      description: "Implement behavior contracts using interfaces, and define partial classes using abstract keywords.",
      links: [{ title: "Oracle Java Tutorial: Interfaces", url: "https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html" }],
      position: { x: 380, y: 220 } },
    { id: "java-exception-handling", kind: "subtopic", label: "Exception Handling",
      description: "Capture runtime exceptions using try/catch/finally blocks and throw customized checked errors.",
      links: [{ title: "Oracle Java Tutorial: Exceptions", url: "https://docs.oracle.com/javase/tutorial/essential/exceptions/" }],
      position: { x: 380, y: 275 } },
    { id: "java-collections", kind: "subtopic", label: "Collections Framework",
      description: "Store sequential items in ArrayLists, link elements, and configure HashSets or HashMap lookups.",
      links: [{ title: "Oracle Java Tutorial: Collections", url: "https://docs.oracle.com/javase/tutorial/collections/" }],
      position: { x: 380, y: 330 } },

    // 3. Advanced
    { id: "java-advanced", kind: "milestone", label: "Advanced",
      description: "Write dynamic types interfaces, utilize declarative streams APIs, and pass functional blocks.",
      position: { x: 60, y: 440 } },
    { id: "java-generics", kind: "subtopic", label: "Generics",
      description: "Build compile-time safe collections and classes that operate over dynamic input types.",
      links: [{ title: "Oracle Java Tutorial: Generics", url: "https://docs.oracle.com/javase/tutorial/java/generics/" }],
      position: { x: 380, y: 440 } },
    { id: "java-streams-api", kind: "subtopic", label: "Streams API",
      description: "Transform, filter, map, and collect elements collections pipelines declaratively.",
      links: [{ title: "Oracle Java Documentation: Streams", url: "https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/package-summary.html" }],
      position: { x: 380, y: 495 } },
    { id: "java-lambda-expressions", kind: "subtopic", label: "Lambda Expressions",
      description: "Write compact, functional blocks as method inputs utilizing single-method interfaces.",
      links: [{ title: "Oracle Java Tutorial: Lambda Expressions", url: "https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html" }],
      position: { x: 380, y: 550 } },

    // 4. Concurrency
    { id: "java-concurrency", kind: "milestone", label: "Concurrency",
      description: "Manage background thread operations, leverage execution thread pools, and manage locks.",
      position: { x: 60, y: 660 } },
    { id: "java-threads", kind: "subtopic", label: "Threads",
      description: "Instantiate concurrent threads, override run behaviors, and execute threads lifecycle paths.",
      links: [{ title: "Oracle Java Tutorial: Defining and Starting a Thread", url: "https://docs.oracle.com/javase/tutorial/essential/concurrency/runthread.html" }],
      position: { x: 380, y: 660 } },
    { id: "java-executors", kind: "subtopic", label: "Executors",
      description: "Orchestrate asynchronous tasks allocations using thread pool service interfaces.",
      links: [{ title: "Oracle Java Tutorial: Executor Interfaces", url: "https://docs.oracle.com/javase/tutorial/essential/concurrency/executors.html" }],
      position: { x: 380, y: 715 } },
    { id: "java-synchronized-locks", kind: "subtopic", label: "synchronized & Locks",
      description: "Coordinate threads access to shared variables scopes using synchronized blocks and ReentrantLocks.",
      links: [{ title: "Oracle Java Tutorial: Synchronization", url: "https://docs.oracle.com/javase/tutorial/essential/concurrency/sync.html" }],
      position: { x: 380, y: 770 } },

    // 5. Ecosystem
    { id: "java-ecosystem", kind: "milestone", label: "Ecosystem",
      description: "Compile and build project files, set up web backends, and run test sweeps.",
      position: { x: 60, y: 880 } },
    { id: "java-maven-gradle", kind: "subtopic", label: "Maven/Gradle",
      description: "Manage script compilation steps, define dependencies mappings, and compile jar packages.",
      links: [{ title: "Apache Maven Project", url: "https://maven.apache.org/" }],
      position: { x: 380, y: 880 } },
    { id: "java-spring-boot", kind: "subtopic", label: "Spring Boot",
      description: "Build production-ready web servers quickly using dependency injection and annotations.",
      links: [{ title: "Spring Boot Docs", url: "https://spring.io/projects/spring-boot" }],
      position: { x: 380, y: 935 } },
    { id: "java-junit", kind: "subtopic", label: "JUnit",
      description: "Validate code behaviors, assert outputs, and verify code coverage maps using JUnit.",
      links: [{ title: "JUnit 5 Documentation", url: "https://junit.org/junit5/docs/current/user-guide/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-java-basics-java-core-concepts", source: "java-basics", target: "java-core-concepts" },
    { id: "e-java-core-concepts-java-advanced", source: "java-core-concepts", target: "java-advanced" },
    { id: "e-java-advanced-java-concurrency", source: "java-advanced", target: "java-concurrency" },
    { id: "e-java-concurrency-java-ecosystem", source: "java-concurrency", target: "java-ecosystem" },
  ],
};
