import { TaskflowContent } from "./types";

export const javascriptTaskflow: TaskflowContent = {
  slug: "javascript",
  title: "JavaScript",
  nodes: [
    // 1. Basics
    { id: "js-basics", kind: "milestone", label: "Basics",
      description: "Learn core variables declarations, basic syntax structures, and execution of functional blocks.",
      position: { x: 60, y: 0 } },
    { id: "js-syntax-variables", kind: "subtopic", label: "Syntax & Variables",
      description: "Declare script scoping flags using modern let, const, and legacy var expressions.",
      links: [{ title: "MDN JS Grammar", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types" }],
      position: { x: 380, y: 0 } },
    { id: "js-data-types", kind: "subtopic", label: "Data Types",
      description: "Differentiate primitive types from complex structures like arrays, objects, and maps.",
      links: [{ title: "MDN JS Data Structures", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures" }],
      position: { x: 380, y: 55 } },
    { id: "js-functions", kind: "subtopic", label: "Functions",
      description: "Write clean execution blocks, using standard block definitions or arrow structures.",
      links: [{ title: "MDN JS Functions Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions" }],
      position: { x: 380, y: 110 } },

    // 2. Control Flow
    { id: "js-control-flow", kind: "milestone", label: "Control Flow",
      description: "Control path logic conditions, repeat actions using loops, and catch unexpected script exceptions.",
      position: { x: 60, y: 220 } },
    { id: "js-loops", kind: "subtopic", label: "Loops",
      description: "Repeat statements using classic for, modern for...of/in, and standard while loops.",
      links: [{ title: "MDN JS Loops Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration" }],
      position: { x: 380, y: 220 } },
    { id: "js-conditionals", kind: "subtopic", label: "Conditionals",
      description: "Route execution code decisions through if/else evaluation flows or clean switch cases.",
      links: [{ title: "MDN JS Control Flow", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling" }],
      position: { x: 380, y: 275 } },
    { id: "js-error-handling", kind: "subtopic", label: "Error Handling",
      description: "Catch unexpected program issues using try/catch blocks and manage customized Error objects.",
      links: [{ title: "MDN JS Error Reference", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" }],
      position: { x: 380, y: 330 } },

    // 3. Advanced Concepts
    { id: "js-advanced-concepts", kind: "milestone", label: "Advanced Concepts",
      description: "Master lexical scope chains, prototype delegations, and asynchronous callback event loops.",
      position: { x: 60, y: 440 } },
    { id: "js-closures", kind: "subtopic", label: "Closures",
      description: "Retain lexical scope access to variables defined outside immediate executing functional blocks.",
      links: [{ title: "MDN JS Closures Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures" }],
      position: { x: 380, y: 440 } },
    { id: "js-prototypes", kind: "subtopic", label: "Prototypes",
      description: "Delegate inherited class functionalities and custom attributes across parent object templates.",
      links: [{ title: "MDN JS Prototypes Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain" }],
      position: { x: 380, y: 495 } },
    { id: "js-async-await", kind: "subtopic", label: "Async/Await",
      description: "Handle deferred runtime outcomes elegantly using ES6 Promise APIs and synchronous-looking keywords.",
      links: [{ title: "MDN JS Async/Await Guide", url: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous" }],
      position: { x: 380, y: 550 } },

    // 4. Browser APIs
    { id: "js-browser-apis", kind: "milestone", label: "Browser APIs",
      description: "Interact with host web page elements, query server endpoints, and persist storage states.",
      position: { x: 60, y: 660 } },
    { id: "js-dom", kind: "subtopic", label: "DOM",
      description: "Traverse, search, update, delete, and add interactive node structures to client pages.",
      links: [{ title: "MDN Document Object Model", url: "https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model" }],
      position: { x: 380, y: 660 } },
    { id: "js-fetch-api", kind: "subtopic", label: "Fetch API",
      description: "Query server routes asynchronously over HTTP networks to fetch data payloads without page reloads.",
      links: [{ title: "MDN Fetch API Guide", url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API" }],
      position: { x: 380, y: 715 } },
    { id: "js-localstorage", kind: "subtopic", label: "LocalStorage",
      description: "Persist stringified payload mappings directly inside the user's browser client sandbox.",
      links: [{ title: "MDN Window LocalStorage", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage" }],
      position: { x: 380, y: 770 } },

    // 5. Modern JS
    { id: "js-modern-js", kind: "milestone", label: "Modern JS",
      description: "Leverage standard ES6 syntax rules to organize and destructure modular code structures.",
      position: { x: 60, y: 880 } },
    { id: "js-es-modules", kind: "subtopic", label: "ES Modules",
      description: "Share variable states and function exports across separate script documents using import/export.",
      links: [{ title: "MDN JS Modules Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules" }],
      position: { x: 380, y: 880 } },
    { id: "js-destructuring", kind: "subtopic", label: "Destructuring",
      description: "Extract list values or attribute mapping values directly into standalone variable declarations.",
      links: [{ title: "MDN JS Destructuring", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment" }],
      position: { x: 380, y: 935 } },
    { id: "js-spread-rest", kind: "subtopic", label: "Spread/Rest",
      description: "Expand data structures or gather multiple elements into single lists using three dots syntax.",
      links: [{ title: "MDN Spread Syntax Reference", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-js-basics-js-control-flow", source: "js-basics", target: "js-control-flow" },
    { id: "e-js-control-flow-js-advanced-concepts", source: "js-control-flow", target: "js-advanced-concepts" },
    { id: "e-js-advanced-concepts-js-browser-apis", source: "js-advanced-concepts", target: "js-browser-apis" },
    { id: "e-js-browser-apis-js-modern-js", source: "js-browser-apis", target: "js-modern-js" },
  ],
};
