import { TaskflowContent } from "./types";

export const kubernetesTaskflow: TaskflowContent = {
  slug: "kubernetes",
  title: "Kubernetes",
  nodes: [
    // 1. Basics
    { id: "k8s-basics", kind: "milestone", label: "Basics",
      description: "Learn core components, control plane operations, and baseline resource units.",
      position: { x: 60, y: 0 } },
    { id: "k8s-pods", kind: "subtopic", label: "Pods",
      description: "Run single or grouped application container workloads, sharing storage resources and network names.",
      links: [{ title: "Kubernetes Pods Documentation", url: "https://kubernetes.io/docs/concepts/workloads/pods/" }],
      position: { x: 380, y: 0 } },
    { id: "k8s-nodes", kind: "subtopic", label: "Nodes",
      description: "Manage worker hosts that run container applications, controlled by the cluster plane.",
      links: [{ title: "Kubernetes Nodes Documentation", url: "https://kubernetes.io/docs/concepts/architecture/nodes/" }],
      position: { x: 380, y: 55 } },
    { id: "k8s-cluster-architecture", kind: "subtopic", label: "Cluster Architecture",
      description: "Understand apiserver, etcd, scheduler, and controller manager interactions in a cluster.",
      links: [{ title: "Kubernetes Architecture", url: "https://kubernetes.io/docs/concepts/architecture/" }],
      position: { x: 380, y: 110 } },

    // 2. Workloads
    { id: "k8s-workloads", kind: "milestone", label: "Workloads",
      description: "Deploy stateless or stateful applications and manage pod count scaling.",
      position: { x: 60, y: 220 } },
    { id: "k8s-deployments", kind: "subtopic", label: "Deployments",
      description: "Manage declarative updates for Pods and ReplicaSets dynamically with rollback options.",
      links: [{ title: "Kubernetes Deployments Docs", url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/" }],
      position: { x: 380, y: 220 } },
    { id: "k8s-replicasets", kind: "subtopic", label: "ReplicaSets",
      description: "Ensure a stable set of replica Pods are executing at any given time.",
      links: [{ title: "Kubernetes ReplicaSets Docs", url: "https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/" }],
      position: { x: 380, y: 275 } },
    { id: "k8s-statefulsets", kind: "subtopic", label: "StatefulSets",
      description: "Manage workloads requiring unique network identifiers and persistent disk mappings.",
      links: [{ title: "Kubernetes StatefulSets Docs", url: "https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/" }],
      position: { x: 380, y: 330 } },

    // 3. Networking
    { id: "k8s-networking", kind: "milestone", label: "Networking",
      description: "Expose container ports, control domain routes, and distribute configuration parameters.",
      position: { x: 60, y: 440 } },
    { id: "k8s-services", kind: "subtopic", label: "Services",
      description: "Expose application Pod networks as abstract network endpoints to direct client requests.",
      links: [{ title: "Kubernetes Services Docs", url: "https://kubernetes.io/docs/concepts/services-networking/service/" }],
      position: { x: 380, y: 440 } },
    { id: "k8s-ingress", kind: "subtopic", label: "Ingress",
      description: "Direct external HTTP/S routing paths to internal cluster services using reverse proxies.",
      links: [{ title: "Kubernetes Ingress Docs", url: "https://kubernetes.io/docs/concepts/services-networking/ingress/" }],
      position: { x: 380, y: 495 } },
    { id: "k8s-configmaps-secrets", kind: "subtopic", label: "ConfigMaps & Secrets",
      description: "Separate environment configs and secure keys from container image code configurations.",
      links: [{ title: "Kubernetes ConfigMaps Guide", url: "https://kubernetes.io/docs/concepts/configuration/configmap/" }],
      position: { x: 380, y: 550 } },

    // 4. Storage
    { id: "k8s-storage", kind: "milestone", label: "Storage",
      description: "Bind network storage partitions to applications, mapping sizes dynamically.",
      position: { x: 60, y: 660 } },
    { id: "k8s-persistent-volumes", kind: "subtopic", label: "Persistent Volumes",
      description: "Provision cluster-level storage resources decoupled from individual Pod lifecycles.",
      links: [{ title: "Kubernetes Persistent Volumes Docs", url: "https://kubernetes.io/docs/concepts/storage/persistent-volumes/" }],
      position: { x: 380, y: 660 } },
    { id: "k8s-pvc", kind: "subtopic", label: "Persistent Volume Claims",
      description: "Request storage capacity allocations matching user specifications from persistent volumes.",
      links: [{ title: "Kubernetes Storage Claims Guide", url: "https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims" }],
      position: { x: 380, y: 715 } },
    { id: "k8s-storage-classes", kind: "subtopic", label: "Storage Classes",
      description: "Define dynamic storage profiles to automatically provision physical disk drives on demand.",
      links: [{ title: "Kubernetes Storage Classes Guide", url: "https://kubernetes.io/docs/concepts/storage/storage-classes/" }],
      position: { x: 380, y: 770 } },

    // 5. Operations
    { id: "k8s-operations", kind: "milestone", label: "Operations",
      description: "Employ packaging systems, query states via CLI, and analyze node logging.",
      position: { x: 60, y: 880 } },
    { id: "k8s-helm", kind: "subtopic", label: "Helm",
      description: "Package, distribute, install, version, and configure Kubernetes manifest files using charts.",
      links: [{ title: "Helm Documentation", url: "https://helm.sh/docs/" }],
      position: { x: 380, y: 880 } },
    { id: "k8s-kubectl", kind: "subtopic", label: "kubectl",
      description: "Interact with apiserver layers to verify configurations, scale services, and inspect logs.",
      links: [{ title: "kubectl Reference Manual", url: "https://kubernetes.io/docs/reference/kubectl/" }],
      position: { x: 380, y: 935 } },
    { id: "k8s-monitoring-logging", kind: "subtopic", label: "Monitoring & Logging",
      description: "Aggregate system health metrics and track server logs using tools like Prometheus and Grafana.",
      links: [{ title: "Kubernetes Logging Architecture", url: "https://kubernetes.io/docs/concepts/cluster-administration/logging/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-k8s-basics-k8s-workloads", source: "k8s-basics", target: "k8s-workloads" },
    { id: "e-k8s-workloads-k8s-networking", source: "k8s-workloads", target: "k8s-networking" },
    { id: "e-k8s-networking-k8s-storage", source: "k8s-networking", target: "k8s-storage" },
    { id: "e-k8s-storage-k8s-operations", source: "k8s-storage", target: "k8s-operations" },
  ],
};
