import { TaskflowContent } from "./types";

export const linuxTaskflow: TaskflowContent = {
  slug: "linux",
  title: "Linux",
  nodes: [
    // 1. Basics
    { id: "linux-basics", kind: "milestone", label: "Basics",
      description: "Navigate directory layouts, execute basic commands, and configure file permissions.",
      position: { x: 60, y: 0 } },
    { id: "linux-fs-hierarchy", kind: "subtopic", label: "File System Hierarchy",
      description: "Understand paths like /etc, /var, /bin, /usr, and how files are stored structurally.",
      links: [{ title: "FHS Specification", url: "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html" }],
      position: { x: 380, y: 0 } },
    { id: "linux-basic-commands", kind: "subtopic", label: "Basic Commands",
      description: "Create, move, list, copy, search, and delete files using commands like cd, ls, mkdir, cp, mv, and rm.",
      links: [{ title: "GNU Coreutils Manual", url: "https://www.gnu.org/software/coreutils/manual/coreutils.html" }],
      position: { x: 380, y: 55 } },
    { id: "linux-permissions", kind: "subtopic", label: "Permissions",
      description: "Configure user, group, and other access flags using chmod, chown, and octal parameters.",
      links: [{ title: "GNU chmod Reference", url: "https://www.gnu.org/software/coreutils/manual/html_node/chmod-invocation.html" }],
      position: { x: 380, y: 110 } },

    // 2. Shell
    { id: "linux-shell", kind: "milestone", label: "Shell",
      description: "Write automated scripts, set environment variables, and chain program outputs.",
      position: { x: 60, y: 220 } },
    { id: "linux-bash-scripting", kind: "subtopic", label: "Bash Scripting",
      description: "Automate system routines using conditions, loop constructs, variable assignments, and exit codes.",
      links: [{ title: "GNU Bash Reference Manual", url: "https://www.gnu.org/software/bash/manual/bash.html" }],
      position: { x: 380, y: 220 } },
    { id: "linux-env-variables", kind: "subtopic", label: "Environment Variables",
      description: "Define export configurations and read variables used by operating processes and users.",
      links: [{ title: "Bash Startup Files Guide", url: "https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html" }],
      position: { x: 380, y: 275 } },
    { id: "linux-pipes-redirection", kind: "subtopic", label: "Pipes & Redirection",
      description: "Direct command inputs/outputs to files or separate commands via operators like |, >, and <.",
      links: [{ title: "GNU Bash Redirection", url: "https://www.gnu.org/software/bash/manual/html_node/Redirections.html" }],
      position: { x: 380, y: 330 } },

    // 3. Process Management
    { id: "linux-process-management", kind: "milestone", label: "Process Management",
      description: "Monitor executing programs, manage server daemons, and control command jobs.",
      position: { x: 60, y: 440 } },
    { id: "linux-ps-top", kind: "subtopic", label: "ps & top",
      description: "List currently active process ids, memory footprints, CPU utilization, and run states.",
      links: [{ title: "procps-ng Utilities docs", url: "https://gitlab.com/procps-ng/procps" }],
      position: { x: 380, y: 440 } },
    { id: "linux-systemd", kind: "subtopic", label: "systemd",
      description: "Configure system service configuration files, reload daemons, and read logs via journalctl.",
      links: [{ title: "systemd Documentation System", url: "https://systemd.io/" }],
      position: { x: 380, y: 495 } },
    { id: "linux-job-control", kind: "subtopic", label: "Job Control",
      description: "Send processes to run in the background, pause jobs, and move them back to the foreground.",
      links: [{ title: "GNU Bash Job Control", url: "https://www.gnu.org/software/bash/manual/html_node/Job-Control-Basics.html" }],
      position: { x: 380, y: 550 } },

    // 4. Networking
    { id: "linux-networking", kind: "milestone", label: "Networking",
      description: "Connect safely to remote servers, query network endpoints, and manage firewall barriers.",
      position: { x: 60, y: 660 } },
    { id: "linux-ssh", kind: "subtopic", label: "SSH",
      description: "Access shell consoles securely using public/private key pairs and remote configurations.",
      links: [{ title: "OpenSSH Documentation", url: "https://www.openssh.com/manual.html" }],
      position: { x: 380, y: 660 } },
    { id: "linux-curl-wget", kind: "subtopic", label: "curl/wget",
      description: "Query HTTP/S URLs, download payloads, and inspect server responses from command line interfaces.",
      links: [{ title: "curl Documentation Guide", url: "https://curl.se/docs/" }],
      position: { x: 380, y: 715 } },
    { id: "linux-firewall", kind: "subtopic", label: "Firewall (ufw/iptables)",
      description: "Configure port blockages and verify connection routings using ufw or raw iptables rules.",
      links: [{ title: "Ubuntu UFW Documentation", url: "https://help.ubuntu.com/community/UFW" }],
      position: { x: 380, y: 770 } },

    // 5. Package Management
    { id: "linux-package-management", kind: "milestone", label: "Package Management",
      description: "Install pre-compiled binary packages, build programs, and update repositories.",
      position: { x: 60, y: 880 } },
    { id: "linux-apt-yum", kind: "subtopic", label: "apt/yum",
      description: "Query package repositories and update system programs using standard distributions managers.",
      links: [{ title: "Debian APT Documentation", url: "https://wiki.debian.org/Apt" }],
      position: { x: 380, y: 880 } },
    { id: "linux-compiling-source", kind: "subtopic", label: "Compiling from Source",
      description: "Download source code libraries and compile them using compilers via make and install scripts.",
      links: [{ title: "GNU Make Reference", url: "https://www.gnu.org/software/make/manual/make.html" }],
      position: { x: 380, y: 935 } },
    { id: "linux-package-repositories", kind: "subtopic", label: "Package Repositories",
      description: "Configure custom PPA pathways or repository mirror lists to source software packages.",
      links: [{ title: "Debian SourcesList Wiki", url: "https://wiki.debian.org/SourcesList" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-linux-basics-linux-shell", source: "linux-basics", target: "linux-shell" },
    { id: "e-linux-shell-linux-process-management", source: "linux-shell", target: "linux-process-management" },
    { id: "e-linux-process-management-linux-networking", source: "linux-process-management", target: "linux-networking" },
    { id: "e-linux-networking-linux-package-management", source: "linux-networking", target: "linux-package-management" },
  ],
};
