import { TaskflowContent } from "./types";

export const mlopsTaskflow: TaskflowContent = {
  slug: "mlops",
  title: "MLOps",
  nodes: [
    // 1. Foundations
    { id: "mlops-foundations", kind: "milestone", label: "Foundations",
      description: "Acquire the core scripting capabilities, versioning strategies, and stages of the machine learning lifecycle.",
      position: { x: 60, y: 0 } },
    { id: "mlops-python", kind: "subtopic", label: "Python",
      description: "Write clean, modular code using standard data packages like NumPy, Pandas, and Scikit-Learn.",
      links: [{ title: "Python Documentation", url: "https://docs.python.org/3/" }],
      position: { x: 380, y: 0 } },
    { id: "mlops-lifecycle", kind: "subtopic", label: "ML Lifecycle",
      description: "Understand the design, collection, labeling, training, optimization, and auditing of models.",
      links: [{ title: "Google ML Crash Course", url: "https://developers.google.com/machine-learning/crash-course" }],
      position: { x: 380, y: 55 } },
    { id: "mlops-git", kind: "subtopic", label: "Git",
      description: "Track code changes, manage model definition branches, and collaborate on codebase repositories.",
      links: [{ title: "Git Documentation", url: "https://git-scm.com/doc" }],
      position: { x: 380, y: 110 } },

    // 2. Experiment Tracking
    { id: "mlops-experiment-tracking", kind: "milestone", label: "Experiment Tracking",
      description: "Log hyperparameters, model training runs, output metrics, and dataset version histories.",
      position: { x: 60, y: 220 } },
    { id: "mlops-mlflow", kind: "subtopic", label: "MLflow",
      description: "Track machine learning experiments, log parameters, and organize model registries.",
      links: [{ title: "MLflow Documentation", url: "https://mlflow.org/docs/latest/index.html" }],
      position: { x: 380, y: 220 } },
    { id: "mlops-wandb", kind: "subtopic", label: "Weights & Biases",
      description: "Visualize network training iterations, compare parameters, and track model artifacts.",
      links: [{ title: "Weights & Biases Docs", url: "https://docs.wandb.ai/" }],
      position: { x: 380, y: 275 } },
    { id: "mlops-dvc", kind: "subtopic", label: "DVC",
      description: "Manage large data files, model binaries, and directories with Git-like hash tracking.",
      links: [{ title: "DVC Documentation", url: "https://dvc.org/doc" }],
      position: { x: 380, y: 330 } },

    // 3. Pipelines
    { id: "mlops-pipelines", kind: "milestone", label: "Pipelines",
      description: "Orchestrate complex data workflows and construct modular ML pipeline steps.",
      position: { x: 60, y: 440 } },
    { id: "mlops-airflow", kind: "subtopic", label: "Airflow",
      description: "Author, schedule, and programmatically monitor workflows using Directed Acyclic Graphs (DAGs).",
      links: [{ title: "Apache Airflow Docs", url: "https://airflow.apache.org/docs/" }],
      position: { x: 380, y: 440 } },
    { id: "mlops-kubeflow", kind: "subtopic", label: "Kubeflow",
      description: "Build, deploy, and manage containerized machine learning pipelines on top of Kubernetes.",
      links: [{ title: "Kubeflow Documentation", url: "https://www.kubeflow.org/docs/" }],
      position: { x: 380, y: 495 } },
    { id: "mlops-feature-stores", kind: "subtopic", label: "Feature Stores",
      description: "Serve consistent data features during both training and real-time model inference loops.",
      links: [{ title: "Feast Feature Store", url: "https://docs.feast.dev/" }],
      position: { x: 380, y: 550 } },

    // 4. Deployment
    { id: "mlops-deployment", kind: "milestone", label: "Deployment",
      description: "Package model binaries and serve predictions reliably to client applications.",
      position: { x: 60, y: 660 } },
    { id: "mlops-docker", kind: "subtopic", label: "Docker",
      description: "Encapsulate training runtimes and serving engines into portable, lightweight containers.",
      links: [{ title: "Docker Docs", url: "https://docs.docker.com/" }],
      position: { x: 380, y: 660 } },
    { id: "mlops-kubernetes", kind: "subtopic", label: "Kubernetes",
      description: "Orchestrate model containers, scale replica counts, and manage networking configurations.",
      links: [{ title: "Kubernetes Documentation", url: "https://kubernetes.io/docs/home/" }],
      position: { x: 380, y: 715 } },
    { id: "mlops-model-serving", kind: "subtopic", label: "Model Serving",
      description: "Deploy prediction endpoints using specialized engines like Triton, Seldon, or FastAPI.",
      links: [{ title: "Triton Inference Server", url: "https://github.com/triton-inference-server/server" }],
      position: { x: 380, y: 770 } },

    // 5. Monitoring
    { id: "mlops-monitoring", kind: "milestone", label: "Monitoring",
      description: "Analyze serving statistics, log data anomalies, and identify shifts in model output distributions.",
      position: { x: 60, y: 880 } },
    { id: "mlops-drift-detection", kind: "subtopic", label: "Model Drift Detection",
      description: "Track performance degradation, data input changes, and prediction probability distributions over time.",
      links: [{ title: "Evidently AI Docs", url: "https://docs.evidentlyai.com/" }],
      position: { x: 380, y: 880 } },
    { id: "mlops-prometheus", kind: "subtopic", label: "Prometheus",
      description: "Scrape system metrics, CPU allocations, memory usage, and endpoint response latencies.",
      links: [{ title: "Prometheus Documentation", url: "https://prometheus.io/docs/introduction/overview/" }],
      position: { x: 380, y: 935 } },
    { id: "mlops-logging", kind: "subtopic", label: "Logging",
      description: "Aggregate request/response payloads and debug stack traces to track down runtime exceptions.",
      links: [{ title: "Python Logging Library", url: "https://docs.python.org/3/library/logging.html" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-mlops-foundations-mlops-experiment-tracking", source: "mlops-foundations", target: "mlops-experiment-tracking" },
    { id: "e-mlops-experiment-tracking-mlops-pipelines", source: "mlops-experiment-tracking", target: "mlops-pipelines" },
    { id: "e-mlops-pipelines-mlops-deployment", source: "mlops-pipelines", target: "mlops-deployment" },
    { id: "e-mlops-deployment-mlops-monitoring", source: "mlops-deployment", target: "mlops-monitoring" },
  ],
};
