import { TaskflowContent } from "./types";

export const networkEngineerTaskflow: TaskflowContent = {
  slug: "network-engineer",
  title: "Network Engineer",
  nodes: [
    // 1. Foundations
    { id: "ne-foundations", kind: "milestone", label: "Foundations",
      description: "Understand the core models of communication, address routing, and IP layout schemas.",
      position: { x: 60, y: 0 } },
    { id: "ne-osi-model", kind: "subtopic", label: "OSI Model",
      description: "Deconstruct networks into 7 structural layers from Physical link signaling to Application interfaces.",
      links: [{ title: "ISO OSI Model Specification", url: "https://www.iso.org/standard/20269.html" }],
      position: { x: 380, y: 0 } },
    { id: "ne-tcp-ip", kind: "subtopic", label: "TCP/IP",
      description: "Analyze packet framing, socket handshakes, sequence numbers, and packet acknowledgements.",
      links: [{ title: "IETF RFC 793 (TCP)", url: "https://datatracker.ietf.org/doc/html/rfc793" }],
      position: { x: 380, y: 55 } },
    { id: "ne-subnetting", kind: "subtopic", label: "Subnetting",
      description: "Calculate network boundaries, host counts, and subnetwork CIDR masks.",
      links: [{ title: "Cisco Subnetting Guide", url: "https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13788-3.html" }],
      position: { x: 380, y: 110 } },

    // 2. Networking Devices
    { id: "ne-devices", kind: "milestone", label: "Networking Devices",
      description: "Understand the hardware components that direct, isolate, and filter traffic payloads.",
      position: { x: 60, y: 220 } },
    { id: "ne-routers", kind: "subtopic", label: "Routers",
      description: "Operate Layer 3 hardware interfaces to forward packet packages across disparate subnetworks.",
      links: [{ title: "Cisco Routing Solutions", url: "https://www.cisco.com/c/en/us/products/routers/index.html" }],
      position: { x: 380, y: 220 } },
    { id: "ne-switches", kind: "subtopic", label: "Switches",
      description: "Manage Layer 2 data frames within local area network segments using MAC address mappings.",
      links: [{ title: "Cisco Switching Solutions", url: "https://www.cisco.com/c/en/us/products/switches/index.html" }],
      position: { x: 380, y: 275 } },
    { id: "ne-firewalls", kind: "subtopic", label: "Firewalls",
      description: "Block unauthorized ports and filter network packets according to strict security rule lists.",
      links: [{ title: "Palo Alto Firewalls Guide", url: "https://www.paloaltonetworks.com/cyberpedia/what-is-a-firewall" }],
      position: { x: 380, y: 330 } },

    // 3. Protocols
    { id: "ne-protocols", kind: "milestone", label: "Protocols",
      description: "Implement structural networks routing, host configuration, and secure tunnels standards.",
      position: { x: 60, y: 440 } },
    { id: "ne-dns", kind: "subtopic", label: "DNS",
      description: "Resolve domain names to server IP addresses using hierarchical name server structures.",
      links: [{ title: "IETF RFC 1035 (DNS)", url: "https://datatracker.ietf.org/doc/html/rfc1035" }],
      position: { x: 380, y: 440 } },
    { id: "ne-dhcp", kind: "subtopic", label: "DHCP",
      description: "Allocate dynamic IP addresses, default gateways, and DNS server addresses to client hosts.",
      links: [{ title: "IETF RFC 2131 (DHCP)", url: "https://datatracker.ietf.org/doc/html/rfc2131" }],
      position: { x: 380, y: 495 } },
    { id: "ne-vpn", kind: "subtopic", label: "VPN",
      description: "Establish encrypted tunnel connections over public infrastructure utilizing IPSec or OpenVPN protocols.",
      links: [{ title: "OpenVPN Documentation", url: "https://openvpn.net/community-resources/" }],
      position: { x: 380, y: 550 } },

    // 4. Network Security
    { id: "ne-network-security", kind: "milestone", label: "Network Security",
      description: "Establish robust boundary access lists, address translation patterns, and monitoring defenses.",
      position: { x: 60, y: 660 } },
    { id: "ne-acls", kind: "subtopic", label: "ACLs",
      description: "Configure sequential permit or deny logic statement blocks targeting source and destination IPs.",
      links: [{ title: "Cisco ACL Configurations", url: "https://www.cisco.com/c/en/us/support/docs/ip/access-lists/26448-10.html" }],
      position: { x: 380, y: 660 } },
    { id: "ne-nat", kind: "subtopic", label: "NAT",
      description: "Map private local address structures to public network address interfaces to save IP allocation pools.",
      links: [{ title: "IETF RFC 3022 (NAT)", url: "https://datatracker.ietf.org/doc/html/rfc3022" }],
      position: { x: 380, y: 715 } },
    { id: "ne-ids-ips", kind: "subtopic", label: "IDS/IPS",
      description: "Inspect network traffic streams for signature patterns to drop malicious payloads immediately.",
      links: [{ title: "Snort IDS Website", url: "https://www.snort.org/" }],
      position: { x: 380, y: 770 } },

    // 5. Tools & Certs
    { id: "ne-tools-certs", kind: "milestone", label: "Tools & Certs",
      description: "Employ network debugging utilities and validate engineering competency through standard certifications.",
      position: { x: 60, y: 880 } },
    { id: "ne-wireshark", kind: "subtopic", label: "Wireshark",
      description: "Inspect frame encapsulation, inspect packet traces, and resolve payload anomalies.",
      links: [{ title: "Wireshark Q&A Wiki", url: "https://wiki.wireshark.org/" }],
      position: { x: 380, y: 880 } },
    { id: "ne-cisco-ccna", kind: "subtopic", label: "Cisco CCNA",
      description: "Validate entry-level networking concepts, routing protocols, IP services, and security practices.",
      links: [{ title: "Cisco CCNA Overview", url: "https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html" }],
      position: { x: 380, y: 935 } },
    { id: "ne-network-monitoring", kind: "subtopic", label: "Network Monitoring",
      description: "Analyze system bandwidth, port utilization, and node responsiveness using SNMP tools.",
      links: [{ title: "Zabbix Monitoring System", url: "https://www.zabbix.com/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-ne-foundations-ne-devices", source: "ne-foundations", target: "ne-devices" },
    { id: "e-ne-devices-ne-protocols", source: "ne-devices", target: "ne-protocols" },
    { id: "e-ne-protocols-ne-network-security", source: "ne-protocols", target: "ne-network-security" },
    { id: "e-ne-network-security-ne-tools-certs", source: "ne-network-security", target: "ne-tools-certs" },
  ],
};
