import { TaskflowContent } from "./types";

export const nextjsTaskflow: TaskflowContent = {
  slug: "nextjs",
  title: "Next.js",
  nodes: [
    // 1. Fundamentals
    { id: "next-fundamentals", kind: "milestone", label: "Fundamentals",
      description: "Learn App Router patterns, component styles, and React Server Components.",
      position: { x: 60, y: 0 } },
    { id: "next-app-router", kind: "subtopic", label: "App Router",
      description: "Route page templates based on directory locations, using the app folder layout structure.",
      links: [{ title: "Next.js App Router Guide", url: "https://nextjs.org/docs/app" }],
      position: { x: 380, y: 0 } },
    { id: "next-pages-layouts", kind: "subtopic", label: "Pages & Layouts",
      description: "Differentiate unique page views from shared layout grids and loading indicator components.",
      links: [{ title: "Next.js Pages and Layouts Docs", url: "https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts" }],
      position: { x: 380, y: 55 } },
    { id: "next-server-components", kind: "subtopic", label: "Server Components",
      description: "Optimize payload sizes by rendering components on the server by default.",
      links: [{ title: "Next.js Server Components Docs", url: "https://nextjs.org/docs/app/building-your-application/rendering/server-components" }],
      position: { x: 380, y: 110 } },

    // 2. Data Fetching
    { id: "next-data-fetching", kind: "milestone", label: "Data Fetching",
      description: "Manage database interactions via Actions, caching controls, and render modes.",
      position: { x: 60, y: 220 } },
    { id: "next-server-actions", kind: "subtopic", label: "Server Actions",
      description: "Trigger asynchronous server routines directly from client forms without configuring endpoints.",
      links: [{ title: "Next.js Server Actions Docs", url: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations" }],
      position: { x: 380, y: 220 } },
    { id: "next-fetch-caching", kind: "subtopic", label: "Fetch Caching",
      description: "Cache HTTP network responses automatically and revalidate cached pages on demand.",
      links: [{ title: "Next.js Data Fetching and Caching", url: "https://nextjs.org/docs/app/building-your-application/data-fetching/fetching" }],
      position: { x: 380, y: 275 } },
    { id: "next-static-dynamic", kind: "subtopic", label: "Static vs Dynamic Rendering",
      description: "Pre-render static layout pages or render routes dynamically per user request.",
      links: [{ title: "Next.js Rendering Modes Docs", url: "https://nextjs.org/docs/app/building-your-application/rendering" }],
      position: { x: 380, y: 330 } },

    // 3. Routing
    { id: "next-routing", kind: "milestone", label: "Routing",
      description: "Map parameters to paths, group similar folders, and intercept routes.",
      position: { x: 60, y: 440 } },
    { id: "next-dynamic-routes", kind: "subtopic", label: "Dynamic Routes",
      description: "Read path parameters using brackets folders and generate paths during build times.",
      links: [{ title: "Next.js Dynamic Routes Docs", url: "https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes" }],
      position: { x: 380, y: 440 } },
    { id: "next-route-groups", kind: "subtopic", label: "Route Groups",
      description: "Organize layout folders without modifying the browser's address path structures using parentheses.",
      links: [{ title: "Next.js Route Groups Docs", url: "https://nextjs.org/docs/app/building-your-application/routing/route-groups" }],
      position: { x: 380, y: 495 } },
    { id: "next-middleware", kind: "subtopic", label: "Middleware",
      description: "Intercept incoming requests to rewrite routes, add headers, or verify authentication status.",
      links: [{ title: "Next.js Middleware Docs", url: "https://nextjs.org/docs/app/building-your-application/routing/middleware" }],
      position: { x: 380, y: 550 } },

    // 4. Optimization
    { id: "next-optimization", kind: "milestone", label: "Optimization",
      description: "Optimize assets load times, structure font files, and add SEO meta headers.",
      position: { x: 60, y: 660 } },
    { id: "next-image-optimization", kind: "subtopic", label: "Image Optimization",
      description: "Compress image assets, prevent layout shifts, and scale layouts dynamically.",
      links: [{ title: "Next.js Image Component Docs", url: "https://nextjs.org/docs/app/building-your-application/optimizing/images" }],
      position: { x: 380, y: 660 } },
    { id: "next-font-optimization", kind: "subtopic", label: "Font Optimization",
      description: "Load local or Google font files during compile time to prevent page rendering jumps.",
      links: [{ title: "Next.js Font Optimization Docs", url: "https://nextjs.org/docs/app/building-your-application/optimizing/fonts" }],
      position: { x: 380, y: 715 } },
    { id: "next-metadata-api", kind: "subtopic", label: "Metadata API",
      description: "Inject document head details and social media cards using static config maps.",
      links: [{ title: "Next.js Metadata API Docs", url: "https://nextjs.org/docs/app/building-your-application/optimizing/metadata" }],
      position: { x: 380, y: 770 } },

    // 5. Deployment
    { id: "next-deployment", kind: "milestone", label: "Deployment",
      description: "Manage deployment configurations, choose output engines, and publish to production hosts.",
      position: { x: 60, y: 880 } },
    { id: "next-env-variables", kind: "subtopic", label: "Environment Variables",
      description: "Expose keys on the client using NEXT_PUBLIC flags or keep them private on the server.",
      links: [{ title: "Next.js Env Variables Docs", url: "https://nextjs.org/docs/app/building-your-application/configuring/environment-variables" }],
      position: { x: 380, y: 880 } },
    { id: "next-vercel-deployment", kind: "subtopic", label: "Vercel Deployment",
      description: "Deploy Next.js apps to Vercel's global CDN network with zero manual config configuration.",
      links: [{ title: "Vercel Next.js Deployment Guide", url: "https://nextjs.org/docs/app/building-your-application/deploying" }],
      position: { x: 380, y: 935 } },
    { id: "next-edge-runtime", kind: "subtopic", label: "Edge Runtime",
      description: "Run light, high-performance scripts near users using specialized, low-latency runtimes.",
      links: [{ title: "Next.js Edge Runtime Docs", url: "https://nextjs.org/docs/app/api-reference/edge" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-next-fundamentals-next-data-fetching", source: "next-fundamentals", target: "next-data-fetching" },
    { id: "e-next-data-fetching-next-routing", source: "next-data-fetching", target: "next-routing" },
    { id: "e-next-routing-next-optimization", source: "next-routing", target: "next-optimization" },
    { id: "e-next-optimization-next-deployment", source: "next-optimization", target: "next-deployment" },
  ],
};
