import { TaskflowContent } from "./types";

export const nodejsTaskflow: TaskflowContent = {
  slug: "nodejs",
  title: "Node.js",
  nodes: [
    // 1. Fundamentals
    { id: "node-fundamentals", kind: "milestone", label: "Fundamentals",
      description: "Understand the non-blocking JavaScript execution engine, modules, and library dependency structures.",
      position: { x: 60, y: 0 } },
    { id: "node-modules", kind: "subtopic", label: "Modules",
      description: "Organize files using CommonJS require patterns or modern ES Module import/export statements.",
      links: [{ title: "Node.js Modules Documentation", url: "https://nodejs.org/api/modules.html" }],
      position: { x: 380, y: 0 } },
    { id: "node-npm", kind: "subtopic", label: "npm",
      description: "Manage script version mappings, dev dependencies, lockfiles, and package scripts inside package.json.",
      links: [{ title: "npm Documentation Portal", url: "https://docs.npmjs.com/" }],
      position: { x: 380, y: 55 } },
    { id: "node-event-loop", kind: "subtopic", label: "Event Loop",
      description: "Grasp how Node handles asynchronous processes using thread pools, microtasks, and execution phases.",
      links: [{ title: "Node.js Event Loop Guide", url: "https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-nexttick" }],
      position: { x: 380, y: 110 } },

    // 2. Core Modules
    { id: "node-core-modules", kind: "milestone", label: "Core Modules",
      description: "Operate the native APIs bundled directly into the runtime installation.",
      position: { x: 60, y: 220 } },
    { id: "node-fs", kind: "subtopic", label: "fs",
      description: "Read, write, delete, stream, and append file system documents asynchronously or synchronously.",
      links: [{ title: "Node.js File System API", url: "https://nodejs.org/api/fs.html" }],
      position: { x: 380, y: 220 } },
    { id: "node-http", kind: "subtopic", label: "http",
      description: "Launch fundamental network server connections, parsing incoming headers and outputting raw payloads.",
      links: [{ title: "Node.js HTTP API", url: "https://nodejs.org/api/http.html" }],
      position: { x: 380, y: 275 } },
    { id: "node-path", kind: "subtopic", label: "path",
      description: "Parse, resolve, parse, join, and normalize directory reference paths across different OS environments.",
      links: [{ title: "Node.js Path API", url: "https://nodejs.org/api/path.html" }],
      position: { x: 380, y: 330 } },

    // 3. Web Frameworks
    { id: "node-web-frameworks", kind: "milestone", label: "Web Frameworks",
      description: "Expedite server setup, request parsing, and API path mapping using popular frameworks.",
      position: { x: 60, y: 440 } },
    { id: "node-express", kind: "subtopic", label: "Express",
      description: "Utilize the minimal, classic middleware-driven routing library to configure REST endpoints.",
      links: [{ title: "Express.js Website", url: "https://expressjs.com/" }],
      position: { x: 380, y: 440 } },
    { id: "node-fastify", kind: "subtopic", label: "Fastify",
      description: "Build high-throughput, low-overhead HTTP interfaces with schema-driven speed.",
      links: [{ title: "Fastify Documentation", url: "https://fastify.dev/" }],
      position: { x: 380, y: 495 } },
    { id: "node-nestjs", kind: "subtopic", label: "NestJS",
      description: "Develop enterprise class, modular backend servers using TypeScript decorators and patterns.",
      links: [{ title: "NestJS Documentation", url: "https://docs.nestjs.com/" }],
      position: { x: 380, y: 550 } },

    // 4. Databases
    { id: "node-databases", kind: "milestone", label: "Databases",
      description: "Connect servers to data store containers and read/write records securely.",
      position: { x: 60, y: 660 } },
    { id: "node-mongodb", kind: "subtopic", label: "MongoDB",
      description: "Store JSON-like documents and query collections using Mongoose object mapping helpers.",
      links: [{ title: "MongoDB Driver Manual", url: "https://www.mongodb.com/docs/drivers/node/current/" }],
      position: { x: 380, y: 660 } },
    { id: "node-postgresql", kind: "subtopic", label: "PostgreSQL",
      description: "Query relational tables, configure relations, and execute transaction updates.",
      links: [{ title: "node-postgres Documentation", url: "https://node-postgres.com/" }],
      position: { x: 380, y: 715 } },
    { id: "node-orms", kind: "subtopic", label: "ORMs",
      description: "Map database relations to programmatic object instances using Prisma, Drizzle, or TypeORM.",
      links: [{ title: "Prisma Documentation", url: "https://www.prisma.io/docs" }],
      position: { x: 380, y: 770 } },

    // 5. Production
    { id: "node-production", kind: "milestone", label: "Production",
      description: "Protect client resources, test scripts, and launch application services to cloud hostings.",
      position: { x: 60, y: 880 } },
    { id: "node-authentication", kind: "subtopic", label: "Authentication",
      description: "Verify client identities using JWT (JSON Web Tokens), cookies, and hashed passwords.",
      links: [{ title: "Passport.js Guide", url: "https://www.passportjs.org/" }],
      position: { x: 380, y: 880 } },
    { id: "node-testing", kind: "subtopic", label: "Testing",
      description: "Validate server functions and inspect integration responses using Jest, Mocha, or Supertest.",
      links: [{ title: "Jest Documentation", url: "https://jestjs.io/" }],
      position: { x: 380, y: 935 } },
    { id: "node-deployment", kind: "subtopic", label: "Deployment",
      description: "Oversee server runs using PM2 processes manager or deploy container instances to cloud runners.",
      links: [{ title: "PM2 Process Manager", url: "https://pm2.keymetrics.io/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-node-fundamentals-node-core-modules", source: "node-fundamentals", target: "node-core-modules" },
    { id: "e-node-core-modules-node-web-frameworks", source: "node-core-modules", target: "node-web-frameworks" },
    { id: "e-node-web-frameworks-node-databases", source: "node-web-frameworks", target: "node-databases" },
    { id: "e-node-databases-node-production", source: "node-databases", target: "node-production" },
  ],
};
