import { TaskflowContent } from "./types";

export const pythonTaskflow: TaskflowContent = {
  slug: "python",
  title: "Python",
  nodes: [
    // 1. Basics
    { id: "py-basics", kind: "milestone", label: "Basics",
      description: "Write basic Python statements, declare dynamic variables, and control conditional code runs.",
      position: { x: 60, y: 0 } },
    { id: "py-syntax-variables", kind: "subtopic", label: "Syntax & Variables",
      description: "Learn white-space indentation rules, comment annotations, and variable declarations.",
      links: [{ title: "Python Tutorial: Informal Introduction", url: "https://docs.python.org/3/tutorial/introduction.html" }],
      position: { x: 380, y: 0 } },
    { id: "py-data-types", kind: "subtopic", label: "Data Types",
      description: "Operate basic types and built-in sequences like lists, dictionaries, tuples, and sets.",
      links: [{ title: "Python Standard Types", url: "https://docs.python.org/3/library/stdtypes.html" }],
      position: { x: 380, y: 55 } },
    { id: "py-control-flow", kind: "subtopic", label: "Control Flow",
      description: "Direct logic checks using if/elif/else blocks, and execute statements repeatedly using for/while loops.",
      links: [{ title: "Python Tutorial: Control Flow Tools", url: "https://docs.python.org/3/tutorial/controlflow.html" }],
      position: { x: 380, y: 110 } },

    // 2. Functions & OOP
    { id: "py-functions-oop", kind: "milestone", label: "Functions & OOP",
      description: "Write reusable functions, construct custom object templates, and segment script namespaces.",
      position: { x: 60, y: 220 } },
    { id: "py-functions", kind: "subtopic", label: "Functions",
      description: "Define execution arguments, assign default values, capture dynamic arguments, and map outputs.",
      links: [{ title: "Python Tutorial: Defining Functions", url: "https://docs.python.org/3/tutorial/controlflow.html#defining-functions" }],
      position: { x: 380, y: 220 } },
    { id: "py-classes", kind: "subtopic", label: "Classes",
      description: "Instantiate class instances, inherit class shapes, and construct initializer methods.",
      links: [{ title: "Python Tutorial: Classes", url: "https://docs.python.org/3/tutorial/classes.html" }],
      position: { x: 380, y: 275 } },
    { id: "py-modules-packages", kind: "subtopic", label: "Modules & Packages",
      description: "Import function scripts and organize directories using dot-notated import paths.",
      links: [{ title: "Python Tutorial: Modules", url: "https://docs.python.org/3/tutorial/modules.html" }],
      position: { x: 380, y: 330 } },

    // 3. Data Handling
    { id: "py-data-handling", kind: "milestone", label: "Data Handling",
      description: "Manage local file scripts, convert dictionary maps, and isolate environment packages.",
      position: { x: 60, y: 440 } },
    { id: "py-file-io", kind: "subtopic", label: "File I/O",
      description: "Open system documents, write records, and utilize safety structures like with blocks.",
      links: [{ title: "Python Tutorial: Reading and Writing Files", url: "https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files" }],
      position: { x: 380, y: 440 } },
    { id: "py-json", kind: "subtopic", label: "JSON",
      description: "Serialize object dictionary structures into formatted strings and parse raw input files.",
      links: [{ title: "Python JSON Library", url: "https://docs.python.org/3/library/json.html" }],
      position: { x: 380, y: 495 } },
    { id: "py-virtual-environments", kind: "subtopic", label: "Virtual Environments",
      description: "Isolate script runtime packages using virtual setups via venv and install dependencies via pip.",
      links: [{ title: "Python Tutorial: Virtual Environments", url: "https://docs.python.org/3/tutorial/venv.html" }],
      position: { x: 380, y: 550 } },

    // 4. Libraries
    { id: "py-libraries", kind: "milestone", label: "Libraries",
      description: "Harness powerful external libraries to process calculations, table data, and HTTP requests.",
      position: { x: 60, y: 660 } },
    { id: "py-numpy", kind: "subtopic", label: "NumPy",
      description: "Optimize calculations and array indexing operations using high-performance multidimensional arrays.",
      links: [{ title: "NumPy Documentation Guide", url: "https://numpy.org/doc/stable/" }],
      position: { x: 380, y: 660 } },
    { id: "py-pandas", kind: "subtopic", label: "Pandas",
      description: "Process, clean, analyze, merge, and group tabular files with efficient DataFrame containers.",
      links: [{ title: "Pandas Getting Started Guides", url: "https://pandas.pydata.org/docs/getting_started/index.html" }],
      position: { x: 380, y: 715 } },
    { id: "py-requests", kind: "subtopic", label: "Requests",
      description: "Perform web requests and interact with server endpoints using standard HTTP parameters.",
      links: [{ title: "Requests Documentation Portal", url: "https://requests.readthedocs.io/" }],
      position: { x: 380, y: 770 } },

    // 5. Frameworks
    { id: "py-frameworks", kind: "milestone", label: "Frameworks",
      description: "Build server runtimes and REST API endpoints using popular Python web engines.",
      position: { x: 60, y: 880 } },
    { id: "py-flask", kind: "subtopic", label: "Flask",
      description: "Develop minimal, lightweight web services using micro-routing controls.",
      links: [{ title: "Flask Documentation Portal", url: "https://flask.palletsprojects.com/" }],
      position: { x: 380, y: 880 } },
    { id: "py-django", kind: "subtopic", label: "Django",
      description: "Establish robust, administrative full-stack databases and backends using batteries-included tools.",
      links: [{ title: "Django Documentation", url: "https://docs.djangoproject.com/" }],
      position: { x: 380, y: 935 } },
    { id: "py-fastapi", kind: "subtopic", label: "FastAPI",
      description: "Construct fast, type-annotated API endpoints utilizing Pydantic constraints and OpenAPI tools.",
      links: [{ title: "FastAPI Documentation Guide", url: "https://fastapi.tiangolo.com/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-py-basics-py-functions-oop", source: "py-basics", target: "py-functions-oop" },
    { id: "e-py-functions-oop-py-data-handling", source: "py-functions-oop", target: "py-data-handling" },
    { id: "e-py-data-handling-py-libraries", source: "py-data-handling", target: "py-libraries" },
    { id: "e-py-libraries-py-frameworks", source: "py-libraries", target: "py-frameworks" },
  ],
};
