import { TaskflowContent } from "./types";

export const qaTaskflow: TaskflowContent = {
  slug: "qa",
  title: "QA",
  nodes: [
    // 1. Foundations
    { id: "qa-foundations", kind: "milestone", label: "Foundations",
      description: "Understand the core concepts of software development lifecycle models and basic bug life cycle stages.",
      position: { x: 60, y: 0 } },
    { id: "qa-sdlc", kind: "subtopic", label: "SDLC",
      description: "Learn software development lifecycle steps and how quality assurance fits within development loops.",
      links: [{ title: "ISTQB SDLC Glossary", url: "https://www.istqb.org/" }],
      position: { x: 380, y: 0 } },
    { id: "qa-testing-types", kind: "subtopic", label: "Testing Types",
      description: "Distinguish between white-box, black-box, functional, non-functional, and unit level checks.",
      links: [{ title: "Guru99 Testing Types", url: "https://www.guru99.com/software-testing-types.html" }],
      position: { x: 380, y: 55 } },
    { id: "qa-bug-tracking", kind: "subtopic", label: "Bug Tracking",
      description: "File defect reports with step-by-step reproductions, log traces, and priority parameters.",
      links: [{ title: "Jira Software Website", url: "https://www.atlassian.com/software/jira" }],
      position: { x: 380, y: 110 } },

    // 2. Manual Testing
    { id: "qa-manual-testing", kind: "milestone", label: "Manual Testing",
      description: "Learn to design comprehensive test procedures and execute verification steps manually.",
      position: { x: 60, y: 220 } },
    { id: "qa-test-case-design", kind: "subtopic", label: "Test Case Design",
      description: "Apply boundary value analysis and equivalence partitioning to define test parameters.",
      links: [{ title: "ISTQB Test Design Specs", url: "https://www.istqb.org/" }],
      position: { x: 380, y: 220 } },
    { id: "qa-exploratory-testing", kind: "subtopic", label: "Exploratory Testing",
      description: "Investigate software features ad-hoc without pre-defined scripts to uncover unexpected edge-cases.",
      links: [{ title: "Agile Alliance Exploratory Testing", url: "https://www.agilealliance.org/glossary/exploratory-testing/" }],
      position: { x: 380, y: 275 } },
    { id: "qa-regression-testing", kind: "subtopic", label: "Regression Testing",
      description: "Execute verification sweeps to ensure code changes have not broken existing behaviors.",
      links: [{ title: "Guru99 Regression Testing", url: "https://www.guru99.com/regression-testing.html" }],
      position: { x: 380, y: 330 } },

    // 3. Automation Testing
    { id: "qa-automation-testing", kind: "milestone", label: "Automation Testing",
      description: "Write programmable test suites that run browsers automatically to inspect interface functionality.",
      position: { x: 60, y: 440 } },
    { id: "qa-selenium", kind: "subtopic", label: "Selenium",
      description: "Utilize WebDriver bindings to write automated scripts targeting legacy or modern browsers.",
      links: [{ title: "Selenium Documentation", url: "https://www.selenium.dev/documentation/" }],
      position: { x: 380, y: 440 } },
    { id: "qa-playwright", kind: "subtopic", label: "Playwright",
      description: "Construct fast, modern end-to-end user journey tests across Chromium, WebKit, and Firefox.",
      links: [{ title: "Playwright Docs", url: "https://playwright.dev/docs/intro" }],
      position: { x: 380, y: 495 } },
    { id: "qa-cypress", kind: "subtopic", label: "Cypress",
      description: "Develop component and end-to-end test cases that execute directly inside the browser runner.",
      links: [{ title: "Cypress Docs", url: "https://docs.cypress.io/" }],
      position: { x: 380, y: 550 } },

    // 4. API Testing
    { id: "qa-api-testing", kind: "milestone", label: "API Testing",
      description: "Inspect raw backend services, validating payload shapes, response status codes, and latency metrics.",
      position: { x: 60, y: 660 } },
    { id: "qa-postman", kind: "subtopic", label: "Postman",
      description: "Organize API collection requests, set environment flags, and script quick assertion workflows.",
      links: [{ title: "Postman Learning Center", url: "https://learning.postman.com/" }],
      position: { x: 380, y: 660 } },
    { id: "qa-rest-assured", kind: "subtopic", label: "REST Assured",
      description: "Employ a Java-based DSL to easily test and validate REST endpoint payloads and headers.",
      links: [{ title: "REST Assured Guide", url: "https://rest-assured.io/" }],
      position: { x: 380, y: 715 } },
    { id: "qa-contract-testing", kind: "subtopic", label: "Contract Testing",
      description: "Ensure consumer and provider microservices conform to agreed integration schemas.",
      links: [{ title: "Pact Foundation Website", url: "https://docs.pact.io/" }],
      position: { x: 380, y: 770 } },

    // 5. Performance & CI
    { id: "qa-performance-ci", kind: "milestone", label: "Performance & CI",
      description: "Determine performance bottlenecks and execute automated test scripts within release pipelines.",
      position: { x: 60, y: 880 } },
    { id: "qa-jmeter", kind: "subtopic", label: "JMeter",
      description: "Construct multi-threaded test models to measure request latencies and check system load limit values.",
      links: [{ title: "Apache JMeter Docs", url: "https://jmeter.apache.org/" }],
      position: { x: 380, y: 880 } },
    { id: "qa-load-testing", kind: "subtopic", label: "Load Testing",
      description: "Evaluate system responses under anticipated concurrent user traffic spikes and limits.",
      links: [{ title: "k6 Documentation", url: "https://grafana.com/docs/k6/latest/" }],
      position: { x: 380, y: 935 } },
    { id: "qa-ci-cd-integration", kind: "subtopic", label: "CI/CD Integration",
      description: "Trigger automation test blocks during code compilation to block regressions before deployment.",
      links: [{ title: "GitHub Actions Guide", url: "https://docs.github.com/en/actions" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-qa-foundations-qa-manual-testing", source: "qa-foundations", target: "qa-manual-testing" },
    { id: "e-qa-manual-testing-qa-automation-testing", source: "qa-manual-testing", target: "qa-automation-testing" },
    { id: "e-qa-automation-testing-qa-api-testing", source: "qa-automation-testing", target: "qa-api-testing" },
    { id: "e-qa-api-testing-qa-performance-ci", source: "qa-api-testing", target: "qa-performance-ci" },
  ],
};
