import { TaskflowContent } from "./types";

export const reactTaskflow: TaskflowContent = {
  slug: "react",
  title: "React",
  nodes: [
    // 1. Fundamentals
    { id: "react-fundamentals", kind: "milestone", label: "Fundamentals",
      description: "Understand the core Virtual DOM engine, component structures, and data attributes.",
      position: { x: 60, y: 0 } },
    { id: "react-jsx", kind: "subtopic", label: "JSX",
      description: "Write declarative HTML-like syntax that maps parameters to standard JavaScript functions.",
      links: [{ title: "React Docs: Writing Markup with JSX", url: "https://react.dev/learn/writing-markup-with-jsx" }],
      position: { x: 380, y: 0 } },
    { id: "react-components", kind: "subtopic", label: "Components",
      description: "Build clean, reusable functional blocks that output page element templates.",
      links: [{ title: "React Docs: Your First Component", url: "https://react.dev/learn/your-first-component" }],
      position: { x: 380, y: 55 } },
    { id: "react-props-state", kind: "subtopic", label: "Props & State",
      description: "Pass read-only attributes downwards and maintain reactive, local variables inside component scopes.",
      links: [{ title: "React Docs: State a Component's Memory", url: "https://react.dev/learn/state-a-components-memory" }],
      position: { x: 380, y: 110 } },

    // 2. Hooks
    { id: "react-hooks", kind: "milestone", label: "Hooks",
      description: "Leverage React hook rules to bind lifecycles and share stateful logic inside components.",
      position: { x: 60, y: 220 } },
    { id: "react-usestate", kind: "subtopic", label: "useState",
      description: "Add local state variables to functional components and trigger re-render loops on modifications.",
      links: [{ title: "React Docs: useState Hook Reference", url: "https://react.dev/reference/react/useState" }],
      position: { x: 380, y: 220 } },
    { id: "react-useeffect", kind: "subtopic", label: "useEffect",
      description: "Synchronize components with external services, manage subscriptions, and trigger side effects.",
      links: [{ title: "React Docs: Synchronizing with Effects", url: "https://react.dev/learn/synchronizing-with-effects" }],
      position: { x: 380, y: 275 } },
    { id: "react-usecontext", kind: "subtopic", label: "useContext",
      description: "Consume global context variables directly without passing props manually down every sub-component level.",
      links: [{ title: "React Docs: useContext Hook Reference", url: "https://react.dev/reference/react/useContext" }],
      position: { x: 380, y: 330 } },

    // 3. Routing & State Management
    { id: "react-routing-state", kind: "milestone", label: "Routing & State Management",
      description: "Map browser address URLs to views and share state models across wide component trees.",
      position: { x: 60, y: 440 } },
    { id: "react-router", kind: "subtopic", label: "React Router",
      description: "Define nested page layouts, manage route histories, and read URL parameters.",
      links: [{ title: "React Router Website", url: "https://reactrouter.com/" }],
      position: { x: 380, y: 440 } },
    { id: "react-state-redux-zustand", kind: "subtopic", label: "Redux/Zustand",
      description: "Manage global state using store patterns with single-source-of-truth architectures.",
      links: [{ title: "Zustand Documentation", url: "https://zustand.docs.pmnd.rs/" }],
      position: { x: 380, y: 495 } },
    { id: "react-context-api", kind: "subtopic", label: "Context API",
      description: "Incorporate React's native global value distribution system to avoid deep props drilling.",
      links: [{ title: "React Docs: Passing Data Deeply with Context", url: "https://react.dev/learn/passing-data-deeply-with-context" }],
      position: { x: 380, y: 550 } },

    // 4. Performance
    { id: "react-performance", kind: "milestone", label: "Performance",
      description: "Identify rendering bottlenecks, cache calculated outputs, and optimize bundle sizes.",
      position: { x: 60, y: 660 } },
    { id: "react-memoization", kind: "subtopic", label: "Memoization",
      description: "Cache callback references and output values across renders using useMemo and useCallback.",
      links: [{ title: "React Docs: memo Reference", url: "https://react.dev/reference/react/memo" }],
      position: { x: 380, y: 660 } },
    { id: "react-code-splitting", kind: "subtopic", label: "Code Splitting",
      description: "Break the main JavaScript bundle into smaller chunks loaded only when routes are accessed.",
      links: [{ title: "React Docs: Code Splitting Guide", url: "https://legacy.reactjs.org/docs/code-splitting.html" }],
      position: { x: 380, y: 715 } },
    { id: "react-lazy", kind: "subtopic", label: "React.lazy",
      description: "Import React components dynamically and display placeholder spinner pages using Suspense.",
      links: [{ title: "React Docs: lazy Reference", url: "https://react.dev/reference/react/lazy" }],
      position: { x: 380, y: 770 } },

    // 5. Ecosystem
    { id: "react-ecosystem", kind: "milestone", label: "Ecosystem",
      description: "Test components, explore production meta-frameworks, and utilize pre-styled UI controls.",
      position: { x: 60, y: 880 } },
    { id: "react-testing", kind: "subtopic", label: "Testing (RTL)",
      description: "Construct client tests focused on component user behavior using React Testing Library.",
      links: [{ title: "React Testing Library Docs", url: "https://testing-library.com/docs/react-testing-library/intro/" }],
      position: { x: 380, y: 880 } },
    { id: "react-nextjs", kind: "subtopic", label: "Next.js",
      description: "Build server-rendered, file-system routed, optimized full-stack React applications.",
      links: [{ title: "Next.js Documentation", url: "https://nextjs.org/docs" }],
      position: { x: 380, y: 935 } },
    { id: "react-component-libraries", kind: "subtopic", label: "Component Libraries",
      description: "Speed up styling setups using pre-configured UI collections like Radix, Tailwind UI, or shadcn/ui.",
      links: [{ title: "Radix UI Primitives", url: "https://www.radix-ui.com/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-react-fundamentals-react-hooks", source: "react-fundamentals", target: "react-hooks" },
    { id: "e-react-hooks-react-routing-state", source: "react-hooks", target: "react-routing-state" },
    { id: "e-react-routing-state-react-performance", source: "react-routing-state", target: "react-performance" },
    { id: "e-react-performance-react-ecosystem", source: "react-performance", target: "react-ecosystem" },
  ],
};
