import { TaskflowContent } from "./types";

export const rustTaskflow: TaskflowContent = {
  slug: "rust",
  title: "Rust",
  nodes: [
    // 1. Basics
    { id: "rust-basics", kind: "milestone", label: "Basics",
      description: "Learn memory safety guarantees, compiler variable flags, and borrowing rules.",
      position: { x: 60, y: 0 } },
    { id: "rust-variables-types", kind: "subtopic", label: "Variables & Types",
      description: "Declare immutable variables by default and handle integer, floating, and char primitive types.",
      links: [{ title: "The Rust Book: Variables and Mutability", url: "https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html" }],
      position: { x: 380, y: 0 } },
    { id: "rust-ownership", kind: "subtopic", label: "Ownership",
      description: "Understand compile-time memory cleanups using value ownership scopes and moves.",
      links: [{ title: "The Rust Book: What is Ownership?", url: "https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html" }],
      position: { x: 380, y: 55 } },
    { id: "rust-borrowing-references", kind: "subtopic", label: "Borrowing & References",
      description: "Access memory values temporarily using shared references or exclusive mutable pointers.",
      links: [{ title: "The Rust Book: References and Borrowing", url: "https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html" }],
      position: { x: 380, y: 110 } },

    // 2. Control Flow & Structs
    { id: "rust-control-flow-structs", kind: "milestone", label: "Control Flow & Structs",
      description: "Write code paths decisions, define custom compound types, and match variables patterns.",
      position: { x: 60, y: 220 } },
    { id: "rust-functions", kind: "subtopic", label: "Functions",
      description: "Write scoped logic functions, define parameters types, and return expression outputs.",
      links: [{ title: "The Rust Book: Functions", url: "https://doc.rust-lang.org/book/ch03-03-how-functions-work.html" }],
      position: { x: 380, y: 220 } },
    { id: "rust-structs-enums", kind: "subtopic", label: "Structs & Enums",
      description: "Construct record structures using structs, and declare multi-variant categories using enums.",
      links: [{ title: "The Rust Book: Structs", url: "https://doc.rust-lang.org/book/ch05-00-structs.html" }],
      position: { x: 380, y: 275 } },
    { id: "rust-pattern-matching", kind: "subtopic", label: "Pattern Matching",
      description: "Evaluate enum values safely using match logic loops and if-let constructs.",
      links: [{ title: "The Rust Book: Patterns and Matching", url: "https://doc.rust-lang.org/book/ch18-00-patterns.html" }],
      position: { x: 380, y: 330 } },

    // 3. Collections & Error Handling
    { id: "rust-collections-errors", kind: "milestone", label: "Collections & Error Handling",
      description: "Handle dynamic heap structures and process errors without runtime exceptions.",
      position: { x: 60, y: 440 } },
    { id: "rust-vectors-hashmaps", kind: "subtopic", label: "Vectors & HashMaps",
      description: "Store sequential index lists in vectors, or key-value data structures inside HashMaps.",
      links: [{ title: "The Rust Book: Common Collections", url: "https://doc.rust-lang.org/book/ch08-00-common-collections.html" }],
      position: { x: 380, y: 440 } },
    { id: "rust-result-option", kind: "subtopic", label: "Result & Option",
      description: "Represent potential operations errors using Result and nullable values using Option.",
      links: [{ title: "The Rust Book: Error Handling", url: "https://doc.rust-lang.org/book/ch09-00-error-handling.html" }],
      position: { x: 380, y: 495 } },
    { id: "rust-error-propagation", kind: "subtopic", label: "Error Propagation",
      description: "Forward call errors upwards to parent function callers using the question mark operator.",
      links: [{ title: "The Rust Book: Recoverable Errors with Result", url: "https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator" }],
      position: { x: 380, y: 550 } },

    // 4. Advanced
    { id: "rust-advanced", kind: "milestone", label: "Advanced",
      description: "Build abstract code models, resolve references lifespans, and iterate over lists.",
      position: { x: 60, y: 660 } },
    { id: "rust-traits-generics", kind: "subtopic", label: "Traits & Generics",
      description: "Define shared class behaviours using traits, and write abstract code scopes using generics.",
      links: [{ title: "The Rust Book: Generic Types, Traits, and Lifetimes", url: "https://doc.rust-lang.org/book/ch10-00-generics-traits-and-lifetimes.html" }],
      position: { x: 380, y: 660 } },
    { id: "rust-lifetimes", kind: "subtopic", label: "Lifetimes",
      description: "Instruct the compiler's borrow checker on reference validity constraints using lifetime tags.",
      links: [{ title: "The Rust Book: Validating References with Lifetimes", url: "https://doc.rust-lang.org/book/ch10-03-lifetime-syntax.html" }],
      position: { x: 380, y: 715 } },
    { id: "rust-closures-iterators", kind: "subtopic", label: "Closures & Iterators",
      description: "Define inline anonymous functions, and loop over sequences using lazy iterators.",
      links: [{ title: "The Rust Book: Functional Language Features", url: "https://doc.rust-lang.org/book/ch13-00-functional-features.html" }],
      position: { x: 380, y: 770 } },

    // 5. Tooling
    { id: "rust-tooling", kind: "milestone", label: "Tooling",
      description: "Manage script compilation steps, download dependencies libraries, and write tests.",
      position: { x: 60, y: 880 } },
    { id: "rust-cargo", kind: "subtopic", label: "Cargo",
      description: "Build code binaries, run dependencies packaging steps, and configure Cargo.toml files.",
      links: [{ title: "The Cargo Book", url: "https://doc.rust-lang.org/cargo/" }],
      position: { x: 380, y: 880 } },
    { id: "rust-crates", kind: "subtopic", label: "Crates.io",
      description: "Publish custom library modules and download community package dependencies.",
      links: [{ title: "Crates.io Package Registry", url: "https://crates.io/" }],
      position: { x: 380, y: 935 } },
    { id: "rust-testing", kind: "subtopic", label: "Testing",
      description: "Write and execute unit tests and integration tests using Rust's built-in test runner framework.",
      links: [{ title: "The Rust Book: Writing Automated Tests", url: "https://doc.rust-lang.org/book/ch11-00-testing.html" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-rust-basics-rust-control-flow-structs", source: "rust-basics", target: "rust-control-flow-structs" },
    { id: "e-rust-control-flow-structs-rust-collections-errors", source: "rust-control-flow-structs", target: "rust-collections-errors" },
    { id: "e-rust-collections-errors-rust-advanced", source: "rust-collections-errors", target: "rust-advanced" },
    { id: "e-rust-advanced-rust-tooling", source: "rust-advanced", target: "rust-tooling" },
  ],
};
