import { TaskflowContent } from "./types";

export const sqlTaskflow: TaskflowContent = {
  slug: "sql",
  title: "SQL",
  nodes: [
    // 1. Basics
    { id: "sql-basics", kind: "milestone", label: "Basics",
      description: "Understand basic query statements, table projections, and data filtering commands.",
      position: { x: 60, y: 0 } },
    { id: "sql-select", kind: "subtopic", label: "SELECT Statements",
      description: "Extract specific fields or calculate columns from a database table.",
      links: [{ title: "PostgreSQL SELECT Docs", url: "https://www.postgresql.org/docs/current/sql-select.html" }],
      position: { x: 380, y: 0 } },
    { id: "sql-where-filtering", kind: "subtopic", label: "WHERE & Filtering",
      description: "Filter returned records matching specific logical criteria and operators.",
      links: [{ title: "PostgreSQL WHERE Clause", url: "https://www.postgresql.org/docs/current/queries-tableexpressions.html#QUERIES-WHERE" }],
      position: { x: 380, y: 55 } },
    { id: "sql-sorting-limiting", kind: "subtopic", label: "Sorting & Limiting",
      description: "Sort resulting records via ORDER BY and limit return counts using LIMIT and OFFSET.",
      links: [{ title: "PostgreSQL LIMIT and OFFSET", url: "https://www.postgresql.org/docs/current/queries-limit.html" }],
      position: { x: 380, y: 110 } },

    // 2. Joins & Relationships
    { id: "sql-joins-relationships", kind: "milestone", label: "Joins & Relationships",
      description: "Query details across linked tables, set reference rules, and nest statements.",
      position: { x: 60, y: 220 } },
    { id: "sql-inner-outer-joins", kind: "subtopic", label: "Inner/Outer Joins",
      description: "Combine records from multiple tables matching primary/foreign fields via INNER, LEFT, RIGHT, or FULL joins.",
      links: [{ title: "PostgreSQL Joins Guide", url: "https://www.postgresql.org/docs/current/tutorial-join.html" }],
      position: { x: 380, y: 220 } },
    { id: "sql-foreign-keys", kind: "subtopic", label: "Foreign Keys",
      description: "Enforce referential constraints to link records between parent and child tables.",
      links: [{ title: "PostgreSQL Foreign Keys", url: "https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-FK" }],
      position: { x: 380, y: 275 } },
    { id: "sql-subqueries", kind: "subtopic", label: "Subqueries",
      description: "Nest query executions within another query's SELECT, FROM, or WHERE statements.",
      links: [{ title: "PostgreSQL Subqueries", url: "https://www.postgresql.org/docs/current/functions-subquery.html" }],
      position: { x: 380, y: 330 } },

    // 3. Aggregation
    { id: "sql-aggregation", kind: "milestone", label: "Aggregation",
      description: "Summarize tables, perform math calculations, and filter aggregated results.",
      position: { x: 60, y: 440 } },
    { id: "sql-groupby", kind: "subtopic", label: "GROUP BY",
      description: "Group query results matching shared values in one or more table fields.",
      links: [{ title: "PostgreSQL GROUP BY Clause", url: "https://www.postgresql.org/docs/current/queries-tableexpressions.html#QUERIES-GROUP" }],
      position: { x: 380, y: 440 } },
    { id: "sql-aggregate-functions", kind: "subtopic", label: "Aggregate Functions",
      description: "Compute metrics like SUM, AVG, COUNT, MIN, and MAX across a group of table values.",
      links: [{ title: "PostgreSQL Aggregate Functions", url: "https://www.postgresql.org/docs/current/functions-aggregate.html" }],
      position: { x: 380, y: 495 } },
    { id: "sql-having", kind: "subtopic", label: "HAVING",
      description: "Filter calculated group outcomes using criteria that cannot be processed in standard WHERE clauses.",
      links: [{ title: "PostgreSQL HAVING Clause", url: "https://www.postgresql.org/docs/current/queries-tableexpressions.html#QUERIES-HAVING" }],
      position: { x: 380, y: 550 } },

    // 4. Advanced
    { id: "sql-advanced", kind: "milestone", label: "Advanced",
      description: "Boost queries response times, write virtual schemas, and manage database update safety.",
      position: { x: 60, y: 660 } },
    { id: "sql-indexes", kind: "subtopic", label: "Indexes",
      description: "Accelerate query lookup performance on tables by building lookup pointer maps (B-Trees).",
      links: [{ title: "PostgreSQL Indexes Guide", url: "https://www.postgresql.org/docs/current/indexes.html" }],
      position: { x: 380, y: 660 } },
    { id: "sql-views", kind: "subtopic", label: "Views",
      description: "Save complex query structures as virtual tables to access computed data layers easily.",
      links: [{ title: "PostgreSQL CREATE VIEW", url: "https://www.postgresql.org/docs/current/sql-createview.html" }],
      position: { x: 380, y: 715 } },
    { id: "sql-transactions", kind: "subtopic", label: "Transactions",
      description: "Execute groups of updates atomically using BEGIN, COMMIT, and ROLLBACK parameters.",
      links: [{ title: "PostgreSQL Transactions", url: "https://www.postgresql.org/docs/current/tutorial-transactions.html" }],
      position: { x: 380, y: 770 } },

    // 5. Database Systems
    { id: "sql-database-systems", kind: "milestone", label: "Database Systems",
      description: "Compare relational engines to choose target storage tools for your application.",
      position: { x: 60, y: 880 } },
    { id: "sql-postgresql", kind: "subtopic", label: "PostgreSQL",
      description: "Leverage an advanced, open-source object-relational database system known for reliability.",
      links: [{ title: "PostgreSQL Documentation", url: "https://www.postgresql.org/docs/" }],
      position: { x: 380, y: 880 } },
    { id: "sql-mysql", kind: "subtopic", label: "MySQL",
      description: "Employ a widely used open-source relational database system common in web frameworks.",
      links: [{ title: "MySQL Reference Manual", url: "https://dev.mysql.com/doc/" }],
      position: { x: 380, y: 935 } },
    { id: "sql-sqlite", kind: "subtopic", label: "SQLite",
      description: "Implement a lightweight, serverless database engine contained within a single file package.",
      links: [{ title: "SQLite Documentation Portal", url: "https://www.sqlite.org/docs.html" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-sql-basics-sql-joins-relationships", source: "sql-basics", target: "sql-joins-relationships" },
    { id: "e-sql-joins-relationships-sql-aggregation", source: "sql-joins-relationships", target: "sql-aggregation" },
    { id: "e-sql-aggregation-sql-advanced", source: "sql-aggregation", target: "sql-advanced" },
    { id: "e-sql-advanced-sql-database-systems", source: "sql-advanced", target: "sql-database-systems" },
  ],
};
