import { TaskflowContent } from "./types";

export const systemDesignTaskflow: TaskflowContent = {
  slug: "system-design",
  title: "System Design",
  nodes: [
    // 1. Foundations
    { id: "sd-foundations", kind: "milestone", label: "Foundations",
      description: "Learn scale mechanics, database trade-offs, and measurement terms.",
      position: { x: 60, y: 0 } },
    { id: "sd-scalability-basics", kind: "subtopic", label: "Scalability Basics",
      description: "Scale applications vertically by adding memory, or horizontally by adding nodes.",
      links: [{ title: "System Design Primer: Scalability", url: "https://github.com/donnemartin/system-design-primer#index-of-system-design-topics" }],
      position: { x: 380, y: 0 } },
    { id: "sd-latency-throughput", kind: "subtopic", label: "Latency vs Throughput",
      description: "Differentiate request response times from transaction processing rates.",
      links: [{ title: "System Design Primer: Latency vs Throughput", url: "https://github.com/donnemartin/system-design-primer#latency-vs-throughput" }],
      position: { x: 380, y: 55 } },
    { id: "sd-cap-theorem", kind: "subtopic", label: "CAP Theorem",
      description: "Understand trade-offs between Consistency, Availability, and Partition tolerance in distributed networks.",
      links: [{ title: "System Design Primer: CAP Theorem", url: "https://github.com/donnemartin/system-design-primer#cap-theorem" }],
      position: { x: 380, y: 110 } },

    // 2. Networking Concepts
    { id: "sd-networking-concepts", kind: "milestone", label: "Networking Concepts",
      description: "Distribute incoming user traffic, parse domain records, and serve resources locally.",
      position: { x: 60, y: 220 } },
    { id: "sd-load-balancing", kind: "subtopic", label: "Load Balancing",
      description: "Distribute client requests across multiple backend servers using hardware/software balancers.",
      links: [{ title: "NGINX Load Balancing Guide", url: "https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/" }],
      position: { x: 380, y: 220 } },
    { id: "sd-cdn", kind: "subtopic", label: "CDN",
      description: "Cache static assets at edge servers globally to reduce page load latencies.",
      links: [{ title: "Cloudflare CDN Overview", url: "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/" }],
      position: { x: 380, y: 275 } },
    { id: "sd-dns", kind: "subtopic", label: "DNS",
      description: "Configure name server paths, zone entries, and route domains requests to server targets.",
      links: [{ title: "Cloudflare DNS Guide", url: "https://www.cloudflare.com/learning/dns/what-is-dns/" }],
      position: { x: 380, y: 330 } },

    // 3. Data Storage
    { id: "sd-data-storage", kind: "milestone", label: "Data Storage",
      description: "Compare database categories, distribute records across servers, and clone tables.",
      position: { x: 60, y: 440 } },
    { id: "sd-sql-nosql", kind: "subtopic", label: "SQL vs NoSQL",
      description: "Differentiate relational schemas from high-performance document or key-value stores.",
      links: [{ title: "AWS Databases Comparison", url: "https://aws.amazon.com/nosql/" }],
      position: { x: 380, y: 440 } },
    { id: "sd-database-sharding", kind: "subtopic", label: "Database Sharding",
      description: "Partition table rows horizontally across multiple database server instances.",
      links: [{ title: "Mongo Sharding Overview", url: "https://www.mongodb.com/docs/manual/sharding/" }],
      position: { x: 380, y: 495 } },
    { id: "sd-replication", kind: "subtopic", label: "Replication",
      description: "Copy database updates to replica nodes to safeguard against server crashes.",
      links: [{ title: "PostgreSQL Replication Guide", url: "https://www.postgresql.org/docs/current/warm-standby.html" }],
      position: { x: 380, y: 550 } },

    // 4. Caching & Messaging
    { id: "sd-caching-messaging", kind: "milestone", label: "Caching & Messaging",
      description: "Store high-frequency keys in-memory and decouple systems using asynchronous buffers.",
      position: { x: 60, y: 660 } },
    { id: "sd-caching-strategies", kind: "subtopic", label: "Caching Strategies",
      description: "Use cache-aside, write-through, or write-behind policies to keep cache and database data synced.",
      links: [{ title: "Redis Documentation Portal", url: "https://redis.io/docs/latest/" }],
      position: { x: 380, y: 660 } },
    { id: "sd-message-queues", kind: "subtopic", label: "Message Queues",
      description: "Buffer task jobs between decoupled services using broker architectures like RabbitMQ.",
      links: [{ title: "RabbitMQ Documentation Guide", url: "https://www.rabbitmq.com/documentation.html" }],
      position: { x: 380, y: 715 } },
    { id: "sd-pubsub", kind: "subtopic", label: "Pub/Sub",
      description: "Broadcast message payloads to multiple subscriber streams concurrently using systems like Apache Kafka.",
      links: [{ title: "Apache Kafka Documentation Guide", url: "https://kafka.apache.org/documentation/" }],
      position: { x: 380, y: 770 } },

    // 5. Architecture Patterns
    { id: "sd-architecture-patterns", kind: "milestone", label: "Architecture Patterns",
      description: "Structure modular components, implement centralized route filters, and protect servers.",
      position: { x: 60, y: 880 } },
    { id: "sd-microservices", kind: "subtopic", label: "Microservices",
      description: "Decompose monolithic applications into independent, isolated service instances.",
      links: [{ title: "Microservices.io Architecture Patterns", url: "https://microservices.io/" }],
      position: { x: 380, y: 880 } },
    { id: "sd-api-gateway", kind: "subtopic", label: "API Gateway",
      description: "Establish a single entry endpoint to route, authenticate, and monitor API traffic.",
      links: [{ title: "Kong API Gateway docs", url: "https://docs.konghq.com/" }],
      position: { x: 380, y: 935 } },
    { id: "sd-rate-limiting", kind: "subtopic", label: "Rate Limiting",
      description: "Restrict requests counts per user to prevent system abuse and safeguard server pools.",
      links: [{ title: "Cloudflare Rate Limiting Guide", url: "https://www.cloudflare.com/learning/bots/what-is-rate-limiting/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-sd-foundations-sd-networking-concepts", source: "sd-foundations", target: "sd-networking-concepts" },
    { id: "e-sd-networking-concepts-sd-data-storage", source: "sd-networking-concepts", target: "sd-data-storage" },
    { id: "e-sd-data-storage-sd-caching-messaging", source: "sd-data-storage", target: "sd-caching-messaging" },
    { id: "e-sd-caching-messaging-sd-architecture-patterns", source: "sd-caching-messaging", target: "sd-architecture-patterns" },
  ],
};
