import { TaskflowContent } from "./types";

export const typescriptTaskflow: TaskflowContent = {
  slug: "typescript",
  title: "TypeScript",
  nodes: [
    // 1. Basics
    { id: "ts-basics", kind: "milestone", label: "Basics",
      description: "Define object shapes, enable strict type checking, and assign return constraints to function scopes.",
      position: { x: 60, y: 0 } },
    { id: "ts-types-interfaces", kind: "subtopic", label: "Types & Interfaces",
      description: "Model structural objects, extend declarations, and assign primitive values aliases.",
      links: [{ title: "TypeScript Handbook: Everyday Types", url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html" }],
      position: { x: 380, y: 0 } },
    { id: "ts-type-inference", kind: "subtopic", label: "Type Inference",
      description: "Understand how the compiler determines variable categories without explicit developer indicators.",
      links: [{ title: "TypeScript Handbook: Type Inference", url: "https://www.typescriptlang.org/docs/handbook/type-inference.html" }],
      position: { x: 380, y: 55 } },
    { id: "ts-functions", kind: "subtopic", label: "Functions",
      description: "Type parameters, map optional fields, and constrain function return values.",
      links: [{ title: "TypeScript Handbook: More on Functions", url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#functions" }],
      position: { x: 380, y: 110 } },

    // 2. Advanced Types
    { id: "ts-advanced-types", kind: "milestone", label: "Advanced Types",
      description: "Develop abstract reusable structures, handle multi-type variables, and resolve categories dynamically.",
      position: { x: 60, y: 220 } },
    { id: "ts-generics", kind: "subtopic", label: "Generics",
      description: "Build functions, helper types, and custom interfaces that work over dynamic types safely.",
      links: [{ title: "TypeScript Handbook: Generics", url: "https://www.typescriptlang.org/docs/handbook/2/generics.html" }],
      position: { x: 380, y: 220 } },
    { id: "ts-union-intersection", kind: "subtopic", label: "Union & Intersection Types",
      description: "Allow multiple valid types via pipe unions or merge shapes via ampersand intersections.",
      links: [{ title: "TypeScript Handbook: Union Types", url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types" }],
      position: { x: 380, y: 275 } },
    { id: "ts-type-guards", kind: "subtopic", label: "Type Guards",
      description: "Instruct the compiler using custom type predicates or standard typeof/instanceof operators.",
      links: [{ title: "TypeScript Handbook: Narrowing", url: "https://www.typescriptlang.org/docs/handbook/2/narrowing.html" }],
      position: { x: 380, y: 330 } },

    // 3. Tooling
    { id: "ts-tooling", kind: "milestone", label: "Tooling",
      description: "Configure compilation parameters, compiler rules, and manage package type bindings.",
      position: { x: 60, y: 440 } },
    { id: "ts-tsconfig", kind: "subtopic", label: "tsconfig",
      description: "Manage compilation options, directory paths, and runtime flags in tsconfig.json.",
      links: [{ title: "TypeScript TSConfig Reference", url: "https://www.typescriptlang.org/tsconfig" }],
      position: { x: 380, y: 440 } },
    { id: "ts-compiler-options", kind: "subtopic", label: "Compiler Options",
      description: "Apply strict checks, determine output target engines, and compile map files.",
      links: [{ title: "TypeScript Compiler Options", url: "https://www.typescriptlang.org/docs/handbook/compiler-options.html" }],
      position: { x: 380, y: 495 } },
    { id: "ts-type-declarations", kind: "subtopic", label: "Type Declarations",
      description: "Write custom declaration files (.d.ts) to define typings for untyped npm packages.",
      links: [{ title: "TypeScript Handbook: Declaration Files", url: "https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html" }],
      position: { x: 380, y: 550 } },

    // 4. OOP in TS
    { id: "ts-oop", kind: "milestone", label: "OOP in TS",
      description: "Construct object hierarchies, apply visibility parameters, and inject annotations.",
      position: { x: 60, y: 660 } },
    { id: "ts-classes", kind: "subtopic", label: "Classes",
      description: "Create object factories, inherit structures, and implement explicit interface constraints.",
      links: [{ title: "TypeScript Handbook: Classes", url: "https://www.typescriptlang.org/docs/handbook/2/classes.html" }],
      position: { x: 380, y: 660 } },
    { id: "ts-access-modifiers", kind: "subtopic", label: "Access Modifiers",
      description: "Encapsulate class members using private, protected, and public keyword rules.",
      links: [{ title: "TypeScript Class Member Visibility", url: "https://www.typescriptlang.org/docs/handbook/2/classes.html#member-visibility" }],
      position: { x: 380, y: 715 } },
    { id: "ts-decorators", kind: "subtopic", label: "Decorators",
      description: "Annotate and intercept class definitions, method executions, and property assignments.",
      links: [{ title: "TypeScript Handbook: Decorators", url: "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators" }],
      position: { x: 380, y: 770 } },

    // 5. Integration
    { id: "ts-integration", kind: "milestone", label: "Integration",
      description: "Leverage TypeScript within standard runtime runtimes and client frameworks.",
      position: { x: 60, y: 880 } },
    { id: "ts-react", kind: "subtopic", label: "Using TS with React",
      description: "Annotate component properties, define state types, and bind custom event types.",
      links: [{ title: "React TypeScript Cheatsheet", url: "https://react-typescript-cheatsheet.netlify.app/" }],
      position: { x: 380, y: 880 } },
    { id: "ts-nodejs", kind: "subtopic", label: "Using TS with Node.js",
      description: "Compile and execute server code using ts-node wrappers or custom build configurations.",
      links: [{ title: "TypeScript Node Guide", url: "https://github.com/tsconfig/bases#readme" }],
      position: { x: 380, y: 935 } },
    { id: "ts-utility-types", kind: "subtopic", label: "Utility Types",
      description: "Use global helpers like Partial, Omit, Pick, and Readonly to reshape existing typings.",
      links: [{ title: "TypeScript Handbook: Utility Types", url: "https://www.typescriptlang.org/docs/handbook/utility-types.html" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-ts-basics-ts-advanced-types", source: "ts-basics", target: "ts-advanced-types" },
    { id: "e-ts-advanced-types-ts-tooling", source: "ts-advanced-types", target: "ts-tooling" },
    { id: "e-ts-tooling-ts-oop", source: "ts-tooling", target: "ts-oop" },
    { id: "e-ts-oop-ts-integration", source: "ts-oop", target: "ts-integration" },
  ],
};
