import { TaskflowContent } from "./types";

export const vueTaskflow: TaskflowContent = {
  slug: "vue",
  title: "Vue",
  nodes: [
    // 1. Fundamentals
    { id: "vue-fundamentals", kind: "milestone", label: "Fundamentals",
      description: "Learn template markup, reactivity hooks, and component parameters configuration.",
      position: { x: 60, y: 0 } },
    { id: "vue-template-syntax", kind: "subtopic", label: "Template Syntax",
      description: "Bind variables attributes and listen to events using v-bind and v-on directives.",
      links: [{ title: "Vue.js Template Syntax Guide", url: "https://vuejs.org/guide/essentials/template-syntax.html" }],
      position: { x: 380, y: 0 } },
    { id: "vue-reactivity-basics", kind: "subtopic", label: "Reactivity",
      description: "Understand Vue's reactive proxy engine and how changes trigger Virtual DOM updates.",
      links: [{ title: "Vue.js Reactivity Fundamentals", url: "https://vuejs.org/guide/essentials/reactivity-fundamentals.html" }],
      position: { x: 380, y: 55 } },
    { id: "vue-components-props", kind: "subtopic", label: "Components & Props",
      description: "Encapsulate template designs into components and pass variables using props.",
      links: [{ title: "Vue.js Component Basics", url: "https://vuejs.org/guide/essentials/component-basics.html" }],
      position: { x: 380, y: 110 } },

    // 2. Composition API
    { id: "vue-composition-api", kind: "milestone", label: "Composition API",
      description: "Write stateful functions, watch variables, and manage component lifecycle phases.",
      position: { x: 60, y: 220 } },
    { id: "vue-ref-reactive", kind: "subtopic", label: "ref & reactive",
      description: "Declare reactive primitives using ref wrappers or complex objects via reactive proxies.",
      links: [{ title: "Vue.js ref() and reactive() API", url: "https://vuejs.org/api/reactivity-core.html" }],
      position: { x: 380, y: 220 } },
    { id: "vue-computed-watch", kind: "subtopic", label: "computed & watch",
      description: "Cache computed properties and run callbacks on reactive variable changes.",
      links: [{ title: "Vue.js Computed Properties", url: "https://vuejs.org/guide/essentials/computed.html" }],
      position: { x: 380, y: 275 } },
    { id: "vue-lifecycle-hooks", kind: "subtopic", label: "Lifecycle Hooks",
      description: "Trigger code logic during onMounted, onUpdated, and onUnmounted stages.",
      links: [{ title: "Vue.js Lifecycle Hooks Guide", url: "https://vuejs.org/guide/essentials/lifecycle.html" }],
      position: { x: 380, y: 330 } },

    // 3. State & Routing
    { id: "vue-state-routing", kind: "milestone", label: "State & Routing",
      description: "Map browser routes and configure centralized state stores.",
      position: { x: 60, y: 440 } },
    { id: "vue-router", kind: "subtopic", label: "Vue Router",
      description: "Configure dynamic page routes, history profiles, and route guard logic filters.",
      links: [{ title: "Vue Router Documentation", url: "https://router.vuejs.org/" }],
      position: { x: 380, y: 440 } },
    { id: "vue-pinia", kind: "subtopic", label: "Pinia",
      description: "Manage global component states using modular, type-safe stores.",
      links: [{ title: "Pinia Documentation Portal", url: "https://pinia.vuejs.org/" }],
      position: { x: 380, y: 495 } },
    { id: "vue-provide-inject", kind: "subtopic", label: "Provide/Inject",
      description: "Pass data down deep component trees without manually prop-drilling.",
      links: [{ title: "Vue.js Provide / Inject Docs", url: "https://vuejs.org/guide/components/provide-inject.html" }],
      position: { x: 380, y: 550 } },

    // 4. Advanced
    { id: "vue-advanced", kind: "milestone", label: "Advanced",
      description: "Author customizable slots, insert custom directives, and render nodes globally.",
      position: { x: 60, y: 660 } },
    { id: "vue-slots", kind: "subtopic", label: "Slots",
      description: "Pass HTML components templates into placeholders to build modular layouts.",
      links: [{ title: "Vue.js Component Slots Docs", url: "https://vuejs.org/guide/components/slots.html" }],
      position: { x: 380, y: 660 } },
    { id: "vue-custom-directives", kind: "subtopic", label: "Custom Directives",
      description: "Author custom attribute behaviors targeting DOM elements lifecycles.",
      links: [{ title: "Vue.js Custom Directives Guide", url: "https://vuejs.org/guide/reusability/custom-directives.html" }],
      position: { x: 380, y: 715 } },
    { id: "vue-teleport", kind: "subtopic", label: "Teleport",
      description: "Render dialogs templates outside the main component tree root safely.",
      links: [{ title: "Vue.js Teleport Component Docs", url: "https://vuejs.org/guide/built-ins/teleport.html" }],
      position: { x: 380, y: 770 } },

    // 5. Ecosystem
    { id: "vue-ecosystem", kind: "milestone", label: "Ecosystem",
      description: "Build server-rendered pages, write vitest checks, and configure bundling rules.",
      position: { x: 60, y: 880 } },
    { id: "vue-nuxtjs", kind: "subtopic", label: "Nuxt.js",
      description: "Develop server-rendered, optimized full-stack applications with built-in routing rules.",
      links: [{ title: "Nuxt.js Documentation Portal", url: "https://nuxt.com/" }],
      position: { x: 380, y: 880 } },
    { id: "vue-testing-vitest", kind: "subtopic", label: "Testing (Vitest)",
      description: "Test components and logic modules using the Vite-native test runner.",
      links: [{ title: "Vitest Documentation Guide", url: "https://vitest.dev/" }],
      position: { x: 380, y: 935 } },
    { id: "vue-vite-integration", kind: "subtopic", label: "Vite Integration",
      description: "Configure bundling, script plugins, and dev server configurations in vite.config.js.",
      links: [{ title: "Vite Guide: Vue Integration", url: "https://vite.dev/guide/" }],
      position: { x: 380, y: 990 } },
  ],
  edges: [
    { id: "e-vue-fundamentals-vue-composition-api", source: "vue-fundamentals", target: "vue-composition-api" },
    { id: "e-vue-composition-api-vue-state-routing", source: "vue-composition-api", target: "vue-state-routing" },
    { id: "e-vue-state-routing-vue-advanced", source: "vue-state-routing", target: "vue-advanced" },
    { id: "e-vue-advanced-vue-ecosystem", source: "vue-advanced", target: "vue-ecosystem" },
  ],
};
